SocialGouv/mano

.github/workflows/production.yml, .k8s/__tests__/__snapshots__/kosko generate --env dev.ts.snap, .k8s/__tests__/__snapshots__/kosko generate --env preprod.ts.snap, .k8s/__tests__/__snapshots__/kosko generate --env prod.ts.snap, .k8s/kosko.toml
=> feat(ci): deploy api in production

.k8s/__tests__/__snapshots__/kosko generate --env dev.ts.snap, .k8s/__tests__/__snapshots__/kosko generate --env preprod.ts.snap, .k8s/__tests__/__snapshots__/kosko generate --env prod.ts.snap, .k8s/components/dashboard.ts
also remove useless registry credentials and increase cpu
=> fix(dashboard): increase k8s startup delay

.github/workflows/review.yml
=> ci: change deploy command

dashboard/src/components/ActionsCalendar.js, dashboard/src/scenes/action/list.js, dashboard/src/scenes/report/view.js
https://trello.com/c/Qyy1Nl3o/462-pouvoir-aller-sur-la-personne-depuis-la-liste-dactions-dans-le-dashboard
=> fix: access person from actions list

website/Dockerfile
nginx4spa is only for client-side single-page applications
=> fix(docker): use nginx image

dashboard/src/scenes/auth/signin.js
https://trello.com/c/iX36rKC0/490-bug-chelou-connexion
=> fix(dashboard): wrong "connect again" behavior on dashboard

api/src/controllers/organisation.js, api/src/sentry.js, dashboard/src/components/table.js, dashboard/src/scenes/organisation/list.js
Après discussion avec Guillaume, ils n'ont pas trop de visibilité sur quelle organisation fait quoi (chiffrée ? active ?)
J'ai ajouté quelques infos, et rendu le tableau triable.
=> feat(dashboard): show more stuff in organisations for superadmin to better pilot

dashboard/src/components/ReportDescriptionModale.js, dashboard/src/components/TableCustomFields.js, dashboard/src/scenes/report/view.js
https://trello.com/c/m5cp0cUq/488-description-dans-le-compte-rendu-ajouter-un-bouton-modfier-qui-ouvre-une-modale-et-qui-la-modifie-de-sorte-quelle-apparaisse-com
https://user-images.githubusercontent.com/31724752/140466487-5dff8ef9-b87a-41b8-b119-db1c7e81adf9.mov
=> fix(dashboard): button for description

dashboard/package.json, dashboard/src/components/Filters.js, dashboard/src/components/charts.js, dashboard/src/scenes/stats/index.js, dashboard/yarn.lock
https://trello.com/c/8gRfyGOf/495-stats-review
- pouvoir afficher en cliquant sur les camemberts les personnes dont les items sont "non renseignés" etc.
- Pouvoir filtrer par "non renseigné"
- Pouvoir afficher les statistiques de sortie de file active
=> feat(dashboard): enhance stats

dashboard/src/scenes/report/view.js
est-ce que pour ce genre de PR on se les check les uns les autres ? 
ou on pousse direct parce que c'est petit, c'est pas très intéressant et ça bugfix ?
(pas de rebellion de ma part, c'est juste question !)
=> fix(dashboard): description linebreaks + prevent XSS

dashboard/src/components/EncryptionKey.js, dashboard/src/services/api.js
Je ne suis pas sûr de tout comprendre mais il semble qu'on n'ait pas la clé dans `API.hashedOrgEncryptionKey` du coup je la retourne dans la fonction ce qui reste `truthy`
=> fix: fix org key

api/src/db/sequelize.js
Je ne sais pas si ça nous apporte grand chose (ça apparait dans sentry)
=> chore: remove useless capture

dashboard/src/scenes/structure/view.js
Trello: https://trello.com/c/osCuIW85/507-la-mise-%C3%A0-jour-dune-structure-existante-ne-fonctionne-pas-sur-le-dashboard-il-ne-se-passe-rien
=> fix(dashboard): structure modification

dashboard/src/scenes/action/CreateAction.js, dashboard/src/scenes/action/view.js
Trello: https://trello.com/c/GAMJ9Am7/496-pouvoir-modifier-l%C3%A9quipe-%C3%A0-laquelle-une-action-est-associ%C3%A9e-%C3%A0-posteriori
J'ai mis la même règle que pour le sélecteur en haut
=> fix(dashboard): team selector for action

api/src/controllers/organisation.js, api/src/db/migrations/2021-11-26-custom-fields-persons.js, api/src/db/migrations/index.js, api/src/models/organisation.js, app/src/components/InputLabelled.js, app/src/contexts/persons.js, app/src/scenes/Persons/FileMedical.js, app/src/scenes/Persons/FileSocial.js, app/src/scenes/Persons/Person.js, dashboard/src/components/EncryptionKey.js, dashboard/src/components/TableCustomFields.js, dashboard/src/recoil/persons.js, dashboard/src/scenes/organisation/view.js, dashboard/src/scenes/person/view.js, dashboard/src/scenes/stats/index.js, tests/src/scripts/db.sql
@arnaudambro Il manque la recherche sur les personnes suivies pour le dashboard, mais je propose de repousser sinon je vais jamais livrer : j'ai laissé trainer la PR une semaine ça commence déjà à faire vieux.
=> feat: custom fields on persons

app/src/contexts/persons.js, dashboard/src/recoil/persons.js
Voir : https://trello.com/c/Y2qRzh2R/525-dossier-m%C3%A9dical-maquettes-faites-page-1-ant%C3%A9c%C3%A9dents-m%C3%A9dicaux
=> feat: add new medical default fields

dashboard/src/recoil/persons.js, dashboard/src/scenes/data-import-export/DownloadExample.js, dashboard/src/scenes/data-import-export/ImportData.js, dashboard/src/scenes/organisation/view.js
Je ne comprends pas pourquoi les champs persos ne s'importent pas correctement. Je crois que j'ai besoin qu'on regarde ensemble @arnaudambro.
=> feat(dashboard): import custom fields

dashboard/src/app.js, dashboard/src/scenes/auth/signin.js, dashboard/src/services/api.js
Pour éviter le mix des states, quand on change d'organisation, il faut reset recoil !
https://github.com/facebookexperimental/Recoil/issues/758
=> feat(dashboard): reset recoil on organisation change

.k8s/__tests__/__snapshots__/kosko generate --env dev.ts.snap, .k8s/__tests__/__snapshots__/kosko generate --env preprod.ts.snap, .k8s/__tests__/__snapshots__/kosko generate --env prod.ts.snap, .k8s/package.json, .k8s/yarn.lock
upgrade metabase to 0.38.6 with a patch for CVE-2021-44228
=> fix: upgrade metabase

.k8s/__tests__/__snapshots__/kosko generate --env dev.ts.snap, .k8s/__tests__/__snapshots__/kosko generate --env preprod.ts.snap, .k8s/__tests__/__snapshots__/kosko generate --env prod.ts.snap, .k8s/components/netpol.ts
Add network isolation at kubernetes level
=> fix(secu): add k8s network policies and update snaps

api/src/controllers/user.js
See: https://trello.com/c/w4VgC7EV/508-bug-connecter-avec-un-autre-utilisateur-fonctionne-mal
Inspired by: https://github.com/betagouv/service-national-universel/pull/827
=> fix(api): fix logout in production

dashboard/src/scenes/stats/index.js
See: https://trello.com/c/arZoQO1X/532-avoir-des-stats-par-territoire
=> feat(dashboard): filter by territory on stats

.k8s/__tests__/__snapshots__/kosko generate --env dev.ts.snap, .k8s/__tests__/__snapshots__/kosko generate --env preprod.ts.snap, .k8s/__tests__/__snapshots__/kosko generate --env prod.ts.snap, .k8s/components/api.ts
Objectif : avoir le dossier des uploads accessible pour l'API via une var d'env.
=> chore(k8s): add uploads storage env var

api/.gitignore, api/src/config.js, api/src/controllers/person.js, dashboard/src/components/Documents.js, dashboard/src/recoil/persons.js, dashboard/src/scenes/person/view.js, dashboard/src/services/api.js, dashboard/src/services/encryption.js, dashboard/src/utils.js
Step 1. Il manque : 
- Intégration dans l'app mobile
- Validation des tailles de fichiers, gestion des erreurs améliorée.
Mais je ne veux pas partir trop longtemps dans mon tunnel, donc j'aimerai bien une revue maintenant (et merger peu de temps après), puis améliorer.
Note pour moi : il faudra ajouter le `STORAGE_DIRECTORY` dans l'env (je ne sais plus du tout comment on fait dans
=> feat(dashboard): upload docs

dashboard/src/app.js, dashboard/src/components/ScrollToTop.js
https://trello.com/c/jsN9IUqI/547-lorsque-je-navigue-sur-mano-bug-affichage
=> feat(dashboard): scroll to top on page change

dashboard/src/recoil/persons.js, dashboard/src/scenes/data-import-export/DownloadExample.js, dashboard/src/scenes/data-import-export/ImportData.js
=> feat(dashboard): import teams

.github/workflows/deactivate.yml
=> chore(ci): fix deactivate action

dashboard/package.json, dashboard/yarn.lock
linked to https://github.com/SocialGouv/mano/pull/322
je ne sais pas pourquoi cette lib est là, et ça a l'air de bien marcher sans, donc je propose de retirer !
=> chore(dashboard): remove web-vitals

app/src/scenes/Actions/Action.js, app/src/scenes/Comments/Comment.js, app/src/scenes/Places/Place.js, app/src/scenes/Structures/Structure.js, app/src/scenes/Territories/Territory.js, app/src/scenes/Territories/TerritoryObservation.js
J'y pense tout le temps et je ne le fais jamais :)
=> fix: typo fr

dashboard/src/services/sentry.js
Voir le commentaire, je pense qu'on a un faux positif dans les erreurs sentry.
=> chore(dashboard): ignore abort error

dashboard/src/scenes/organisation/view.js
=> feat(import): improve description in import

dashboard/src/scenes/data-import-export/DownloadExample.js
=> feat(dashboard): more info in download example

dashboard/src/utils.js
Cf: https://trello.com/c/a3c2JQ6Y/558-import-de-comptes (premier point du deuxième bloc).
L'idée c'est qu'on puisse importer les booleens en mettant oui non
=> fix(dashboard): import boolean

dashboard/src/scenes/data-import-export/ImportData.js, dashboard/src/utils.js
See: https://trello.com/c/a3c2JQ6Y/558-import-de-comptes
En forçant l'import à transformer les dates dans un certain format pour le champ `w` on s'en sort mieux.
=> fix(dashboard): old dates in import aka 1940 bug

app/ios/Podfile.lock, app/package.json, app/src/scenes/Login/Login.js, app/src/services/api-interface-with-app.js, app/src/services/dataManagement.js, app/yarn.lock
fix: https://trello.com/c/4ig4OAtn/565-app-bug-donn%C3%A9es-de-differentes-orga-m%C3%A9lang%C3%A9es
Nettoyage du cache quand un utilisateur change de numéro d'organisation
=> fix(app): remove cache when changing organisation

dashboard/src/components/Loader.js, dashboard/src/scenes/action/CreateAction.js, dashboard/src/scenes/auth/signin.js, dashboard/src/scenes/person/CreatePerson.js, dashboard/src/scenes/place/list.js, dashboard/src/scenes/report/list.js, dashboard/src/scenes/search/index.js, dashboard/src/scenes/stats/index.js, dashboard/src/scenes/territory/list.js
Mon code est pas ouf et il est spaghettiesque, mais je pense qu'il fait le job sans trop demander de révolutionner le système de refresh. Je pense qu'on le révolutionnera quand on aura un peu plus de temps, pour l'instant il faut le stabiliser.
L'idée c'est : 
Le Loader est tout le temps présent, donc autant l'utiliser pour piloter le refresher plutôt que de mettre direct dans des composants qui risquent de se décharger à tout moment. Donc les composants appellent juste un effect du loader en lui disant de quoi ils ont besoin et le loader se charge de refresh en espérant le faire proprement.
On itérera en refaisant tout.
Ton avis et tes tests m'intéressent sur celle là @arnaudambro
=> fix(dashboard): fix refresher bugs

app/src/scenes/Actions/Action.js, app/src/scenes/Comments/Comment.js, app/src/scenes/Places/NewPlaceForm.js, dashboard/src/components/Places.js, dashboard/src/recoil/reports.js, dashboard/src/scenes/report/view.js
par contre je n'ai pas vu le problème avec `outOfActiveList` ?
=> fix(app,dashboard):  last fixes before encryption

dashboard/src/components/Filters.js, dashboard/src/recoil/persons.js
=> feat(dashboard): improve filters for persons

app/src/services/api.js
j'ai l'impression que chez moi ça fonctionne mieux comme ça...
=> fix(app): expired session

dashboard/src/services/dataManagement.js
https://sentry.io/organizations/selego/issues/3060511896/?project=5384501&referrer=slack
=> fix(dashboard): stop throw error on fail api request

app/src/scenes/Actions/Action.js
bon, ça marche proprement, si tu veux ne pas tester tu peux
=> fix(app): duplicate comments on duplicate action

api/src/controllers/organisation.js, api/src/controllers/user.js, api/src/utils.js, dashboard/src/utils.js, tests/src/__tests__/report.test.ts
En fait on n'a pas besoin de generate password du tout vu qu'on initialize les comptes qui devront se créer un mot de passe
=> fix: remove unsecure password generation

app/src/scenes/Actions/Action.js
=> fix(app): action empty #MANO-99

api/src/controllers/comment.js
Testée par Raph (mobile + dashboard), tests auto OK ✅
=> chore(security): comment controller

api/src/controllers/organisation.js
Testée par Raph (mobile + dashboard), en attente des tests autos.
=> chore(security): organisation controller

api/src/controllers/place.js
Testée par Raph (mobile + dashboard), tests auto OK
=> chore(security): place controller

api/src/controllers/report.js
Testée par Raph (mobile + dashboard), tests auto OK
=> chore(security): report controller

api/src/controllers/structure.js
Testée par Raph (mobile + dashboard), test auto OK ✅
=> chore(security): structure controller

api/src/controllers/team.js
Testée par Raph (mobile + dashboard), tests auto OK
=> chore(security): team controller

api/src/controllers/territory.js, api/src/controllers/territoryObservation.js
Testée par Raph (mobile + dashboard), tests auto OK
=> chore(security): territory controller

api/src/controllers/user.js
Testée par Raph (mobile + dashboard), en attente des tests autos.
~~AH les tests pètent POUR DE VRAI :D On dirait que la mise à jour ne marche plus dans certains cas.~~
=> chore(security): user controller

dashboard/src/components/CustomFieldInput.js, dashboard/src/scenes/action/CreateAction.js, dashboard/src/scenes/action/view.js, dashboard/src/scenes/organisation/view.js, dashboard/src/scenes/person/view.js, dashboard/src/scenes/team/view.js
See: https://trello.com/c/ifGwHWEy/602-bug-web-champs
=> fix(dashboard): boolean custom field display

api/src/index.js, dashboard/package.json, dashboard/src/app.js, dashboard/src/components/VersionOutdatedAlert.js, dashboard/src/recoil/apiVersion.js, dashboard/src/services/api.js, dashboard/yarn.lock
- L'API envoie tout le temps un header avec sa version en cours
- Côté front ça set l'info dans recoil
- Si l'API est en avance on invite à update le front
=> feat(dashboard): outdated version checker

dashboard/src/scenes/person/DeletePerson.js, dashboard/src/scenes/person/view.js
=> feat(dashboard): warning before delete person

dashboard/src/components/header/index.js, dashboard/src/scenes/action/view.js, dashboard/src/scenes/person/view.js, dashboard/src/scenes/place/view.js, dashboard/src/scenes/structure/view.js, dashboard/src/scenes/team/view.js, dashboard/src/scenes/territory/view.js, dashboard/src/scenes/user/view.js
Pas important j'en avais juste marre.
=> chore(dashboard): smaller header

dashboard/src/components/TableCustomFields.js
=> chore(dashboard): cant create a custom field with no name

dashboard/src/components/Filters.js
=> chore(dashboard): fix filter css to be above pagination

dashboard/src/scenes/action/list.js, dashboard/src/scenes/person/list.js, dashboard/src/scenes/place/list.js, dashboard/src/scenes/reception/view.js, dashboard/src/scenes/report/list.js, dashboard/src/scenes/report/view.js, dashboard/src/scenes/structure/list.js, dashboard/src/scenes/team/list.js, dashboard/src/scenes/territory/list.js, dashboard/src/scenes/user/list.js
moi j'en avais marre aussi, mais aussi sur les listes !
j'ai rajouté une modif supplémentaire dans la liste d'actions
=> chore(dashboard): headers in list

sonar-project.properties
j'ai pas tester, j'imagine qu'il faut merger pour tester
mais ça pourrait marcher
=> chore: remove duplicate check from sonarcloud

api/src/controllers/user.js
Pas important cf: https://github.com/SocialGouv/mano/issues/504
=> refactor(api): remove useless code (fk deletion)

dashboard/src/scenes/data-import-export/ImportData.js, dashboard/src/scenes/data-import-export/importSanitizer.js, dashboard/src/utils.js
Pour corriger l'import des excel de compte sur les `yes-no` j'ai fait un peu de refactor (si ça se trouve c'est useless mais je m'y repère mieux et ça fait des lignes en moins)
=> fix(dashboard): sanitize imports

api/src/controllers/user.js, api/src/db/migrations/2022-03-21-debug-app-dashboard-user.js, api/src/db/migrations/index.js, api/src/models/user.js, app/src/scenes/Login/Login.js, app/src/services/api.js, dashboard/package.json, dashboard/src/scenes/auth/signin.js, dashboard/yarn.lock
Bon je pense que côté dashboard tu ne vas pas avoir grand chose à dire, mais peut-être que l'app tu auras, parce que j'ai mis beaucoup d'infos
Je n'ai pas d'avis sur le sujet, savoir si c'est trop, trop intrusif ou quoique ce soit : je me suis dit que ça ne faisait pas de mal donc j'ai mis toutes les infos suivantes
je suis ouvert pour en retirer !
=> chore: add debug infos for app

dashboard/src/scenes/auth/signin.js
Enfin je sais pas si c'est useless mais ça avai l'air. Du coup je te mets en relecteur au cas où .....
=> refactor(dashboard): remove useless code

app/index.js
J'ai mis les même que dans le dashboard.
=> fix(app): ignore noisy errors for mobile

dashboard/src/config.js, dashboard/src/scenes/auth/signin.js
Juste parce que j'en peux pluuuus.
=> chore(dashboard): accept env org key local

api/src/controllers/organisation.js, app/src/scenes/Persons/FileMedical.js, dashboard/src/components/TableCustomFields.js, dashboard/src/components/table.js, dashboard/src/scenes/organisation/view.js, dashboard/src/scenes/person/view.js
See: https://trello.com/c/vj7vQYFi/619-dossier-m%C3%A9dical
> Champ visible dossier médical uniquement VS visible pour tous
=> feat(dashboard,app): only healthcare professional

app/src/scenes/Persons/NewPersonForm.js
See: https://github.com/SocialGouv/mano/issues/558
Part 2 (app)
=> feat(app): suggest team association when create person

dashboard/src/scenes/place/list.js, dashboard/src/scenes/place/view.js, dashboard/src/scenes/search/index.js
à voir avec https://github.com/SocialGouv/mano/issues/532#issuecomment-1085895880
=> chore: remove dangerouslySetInnerHTML when applicable

app/src/scenes/Actions/NewActionForm.js
Je ne sais pas trop si ça ne va pas résoudre aussi ça : https://sentry.io/organizations/selego/issues/3158463958
=> fix(app): display person name when create action for multiple users (use decrypted data)

app/src/scenes/Login/Login.js
Fix: https://trello.com/c/MXQXKbDO/617-il-est-possible-de-se-connecter-sans-la-cl%C3%A9-sur-mobile-apr%C3%A8s-une-d%C3%A9connexion
=> fix(security): empty key on mobile

dashboard/src/scenes/reception/SelectAndCreatePerson.js
https://trello.com/c/35yNjgMR/635-en-tant-que-pro-daccueil-jai-besoin-de-pouvoir-visualiser-la-date-de-naissance-des-personnes-auquelles-jajoute-un-passage-direct
=> feat(dashboard): display birthdate on reception

api/src/controllers/organisation.js, api/src/controllers/public.js, app/src/components/Loader.js, dashboard/src/components/Loader.js
Parce que sinon ça veut dire que tout le monde peut voir les stats orga par orga.
Le problème c'est que ça force à release l'app :/
=> fix(security): separate public and private routes

app/src/recoil/actions.js, app/src/scenes/Actions/Action.js, app/src/scenes/Actions/ActionRow.js, app/src/scenes/Actions/NewActionForm.js, dashboard/src/components/ActionsCalendar.js, dashboard/src/components/ExclamationMarkButton.js, dashboard/src/components/table.js, dashboard/src/recoil/actions.js, dashboard/src/scenes/action/CreateAction.js, dashboard/src/scenes/action/list.js, dashboard/src/scenes/action/view.js, dashboard/src/scenes/person/view.js, dashboard/src/scenes/report/view.js
C'est la première étape de ça : https://trello.com/c/Z0VrLefp/633-action-urgente-step-1-rajouter-la-notion-durgent-et-surligner.
L'idée pour l'instant c'est de rajouter la possibilité de pouvoir dire quand on crée/modifie une action qu'elle est prioritaire. Et ça la surligne dans les différents écrans.
Création/modification          |  Consultation (exemple sur un écran)
:-------------------------:|:-------------------------:
Agenda       |  Modification | Consultation |
:-------------------------:|:-------------------------:|:-------------------------:
=> feat(app, dashboard): action urgent

dashboard/src/scenes/person/view.js
see: https://trello.com/c/7NW0DPDg/636-en-tant-que-ts-jai-besoin-de-filtrer-les-actions-par-categories-daction-depuis-le-dossier-de-la-personne-suivie-afin-de-mieux-ac
j'ai décidé de mettre le statut aussi pour habiller et parce que ça me parait logique si j'ai une grande liste.
=> feat(dashboard): filter by category and status on person

dashboard/src/components/TableCustomFields.js
=> fix(dashboard): table custom field mutations

api/package.json, api/src/controllers/user.js, api/src/utils.js, api/yarn.lock
Fix https://github.com/SocialGouv/mano/security/code-scanning/11 and https://github.com/SocialGouv/mano/security/code-scanning/10
=> fix(security): add sanitizer, sanitize name and email before returning

dashboard/src/scenes/stats/index.js, tests/src/__tests__/report.test.ts
=> feat(dashboard): stats for passages with genders

app/src/components/Loader.js, app/src/services/dataManagement.js, dashboard/src/components/Loader.js
+ un petit fix: j'avais changé le `lastRefresh` par défaut à `null`, j'aurais pas dû, je retourne à `0` !
=> feat(dashboard,app): auto refresh

dashboard/package.json, dashboard/src/components/Loader.js, dashboard/src/recoil/actions.js, dashboard/src/recoil/comments.js, dashboard/src/recoil/passages.js, dashboard/src/recoil/persons.js, dashboard/src/recoil/places.js, dashboard/src/recoil/relPersonPlace.js, dashboard/src/recoil/reports.js, dashboard/src/recoil/territory.js, dashboard/src/recoil/territoryObservations.js, dashboard/src/scenes/auth/signin.js, dashboard/src/services/dataManagement.js, dashboard/yarn.lock, tests/src/__tests__/report.test.ts, tests/src/__tests__/services.test.ts
C'est en cherchant à améliorer ma culture générale sur les Web Workers et Service Workers ce week-end que je suis [Cache API](https://developer.mozilla.org/en-US/docs/Web/API/Cache) et de fil en aiguille je suis (re)tombé sur [IndexedDB API](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) et sur le lien de bas de page:
> Note: IndexedDB API is powerful, but may seem too complicated for simple cases. If you'd prefer a simple API, try libraries in [See also](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API#see_also) section that make IndexedDB more programmer-friendly.
De là je suis tombé sur [localForage](https://github.com/localForage/localForage), 20k stars sur github, ça a l'air de rouler...
Donc j'ai mis ça sur le dashboard, c'est hyper simple et ça marche …
=> feat: cache in dashboard

dashboard/src/components/Loader.js, dashboard/src/recoil/actions.js, dashboard/src/recoil/comments.js, dashboard/src/recoil/passages.js, dashboard/src/recoil/persons.js, dashboard/src/recoil/places.js, dashboard/src/recoil/relPersonPlace.js, dashboard/src/recoil/reports.js, dashboard/src/recoil/territory.js, dashboard/src/recoil/territoryObservations.js, dashboard/src/services/dataManagement.js
https://sentry.io/organizations/selego/issues/3229174616/?project=5384501&referrer=slack
=> fix(dashboard): disable cache when not available

dashboard/src/scenes/person/MedicalFile.js, dashboard/src/scenes/person/view.js
…medical
OUPS
j'ai pushé `feat(dashboard): no need end date on treatment` sur la même branche alors que je pensais que c'était une branche dédiée...
bon je laisse là quand même si tu me l'autorises ! 😬
=> feat(dashboard): show medical infos for professional only on dossier medical

dashboard/src/scenes/person/MedicalFile.js
=> fix(dashboard): rearrange consultations columns

dashboard/src/components/ActionsCalendar.js, dashboard/src/components/ConsultationButton.js, dashboard/src/components/drawer.js, dashboard/src/recoil/selectors.js, dashboard/src/scenes/action/list.js, dashboard/src/scenes/person/MedicalFile.js, dashboard/src/scenes/reception/view.js, tests/src/__tests__/organisation.test.ts
https://trello.com/c/TBhDeZGG/656-les-consultations-ne-saffichent-pas-dans-lagenda
bon, je suis pas sûr du truc, surtout niveau code
J'ai fait cette ligne là dans un sélecteur pour les consultations
https://github.com/SocialGouv/mano/blob/dd55800d4de5bc1d5f37948320e75948faa19ea9/dashboard/src/recoil/selectors.js#L42
et après j'ai aussi ça
https://github.com/SocialGouv/mano/blob/dd55800d4de5bc1d5f37948320e75948faa19ea9/dashboard/src/components/ActionsCalendar.js#L61-L67
je suis pas méga fan, ça fait un peu un mélange de chou et carotte "volontaire"
mais bon...
je me dis: soit en remet en question l'idée d'afficher actions et consultations en même temps, soit j'ai pas beaucoup d'autre idée !
=> feat(dashboard): show consultations within actions

dashboard/src/components/Notification.js, dashboard/src/components/TopBar.js, tests/src/__tests__/services.test.ts
Les choix que j'ai fait : 
- ça affiche toutes les actions "urgentes"+"à faire" (peu importe la date passée ou futur)
- C'est seulement pour l'équipe sélectionnée
- Pour l'instant seules les actions peuvent être urgentes, dans le futur probablement d'autres trucs
https://user-images.githubusercontent.com/1575946/166466280-51126a08-7325-44a2-8d62-fa4fa5b664fa.mov
=> feat(dashboard): notification for action urgente

dashboard/src/components/Loader.js, dashboard/src/recoil/actions.js, dashboard/src/recoil/comments.js, dashboard/src/recoil/passages.js, dashboard/src/recoil/persons.js, dashboard/src/recoil/places.js, dashboard/src/recoil/relPersonPlace.js, dashboard/src/recoil/reports.js, dashboard/src/recoil/territory.js, dashboard/src/recoil/territoryObservations.js, dashboard/src/scenes/auth/signin.js, dashboard/src/services/dataManagement.js
ça a l'air de marcher chez moi !
=> fix(dashboard): cache key in index db

app/src/components/Row.js, app/src/scenes/Menu/Menu.js, app/src/scenes/Reports/ReportsCalendar.js
Qu'en penses-tu ?
https://user-images.githubusercontent.com/31724752/171851368-a28bd32c-239b-45c1-9144-4586c570c2a2.mov
=> fix(app): crash on logout + logout button position and color

api/src/controllers/action.js, api/src/controllers/comment.js, api/src/controllers/consultation.js, api/src/controllers/medicalFile.js, api/src/controllers/passage.js, api/src/controllers/person.js, api/src/controllers/place.js, api/src/controllers/relPersonPlace.js, api/src/controllers/report.js, api/src/controllers/territory.js, api/src/controllers/territoryObservation.js, api/src/controllers/treatment.js
=> fix(api): keep encrypted fields even if soft delete

dashboard/src/scenes/stats/index.js
https://trello.com/c/qRTgM8yo/709-dans-les-statistiques-globales-le-nombre-total-dactions-qui-saffiche-sur-longlet-général-est-différent-du-nombre-total-dactions
=> fix(dashboard): show actions in stats with wrong category

api/src/controllers/user.js, app/src/recoil/selectors.js
=> fix(app,api): sonarcloud bugs

dashboard/package.json, dashboard/src/components/Comments.js, dashboard/src/components/CreateObservation.js, dashboard/src/components/CustomFieldDisplay.js, dashboard/src/components/CustomFieldInput.js, dashboard/src/components/DateRangePickerWithPresets.js, dashboard/src/components/DeleteOrganisation.js, dashboard/src/components/EncryptionKey.js, dashboard/src/components/NightSessionModale.js, dashboard/src/components/Passage.js, dashboard/src/datepicker.css, dashboard/src/index.js, dashboard/src/scenes/action/CreateAction.js, dashboard/src/scenes/person/DeletePerson.js, dashboard/src/scenes/reception/SelectAndCreatePerson.js, dashboard/src/scenes/territory/view.js, dashboard/yarn.lock
=> fix(dashboard): remove react-dates

app/src/utils/colors.js, dashboard/src/components/Card.js, dashboard/src/config.js
validé par Guillaume, qu'en penses-tu ?
=> fix(app,dashboard): colors for accessibility

dashboard/src/scenes/stats/index.js
https://trello.com/c/Cp3s6QIY/705-les-personnes-sorties-de-file-active
=> fix(dashboard): exclude out of active list in stats when pertinent

dashboard/src/scenes/reception/SelectAndCreatePerson.js
https://trello.com/c/nO5X3PwI/716-empêcher-la-création-automatique-de-personnes-avec-la-toucher-entrée-lorsquon-recherche-quelquun-dans-laccueil
=> fix(dashboard): prevent create person on creatable on Enter press

dashboard/src/components/Comments.js, dashboard/src/components/CreateObservation.js, dashboard/src/components/EncryptionKey.js, dashboard/src/components/ModalConfirm.js, dashboard/src/components/NightSessionModale.js, dashboard/src/components/OnboardingEndModal.js, dashboard/src/components/Passage.js, dashboard/src/components/Places.js, dashboard/src/components/ReportDescriptionModale.js, dashboard/src/components/SortableGrid.js, dashboard/src/components/TableCustomFields.js, dashboard/src/scenes/account.js, dashboard/src/scenes/action/CreateAction.js, dashboard/src/scenes/data-import-export/ImportData.js, dashboard/src/scenes/organisation/list.js, dashboard/src/scenes/person/CreatePerson.js, dashboard/src/scenes/person/MedicalFile.js, dashboard/src/scenes/person/OutOfActiveList.js, dashboard/src/scenes/place/list.js, dashboard/src/scenes/structure/list.js, dashboard/src/scenes/team/list.js, dashboard/src/scenes/territory/list.js, dashboard/src/scenes/user/list.js
https://trello.com/c/A81N980X/700-empêcher-la-fermeture-quand-clic-zone-grisée
=> fix(dashboard): prevent outside click of modal

dashboard/src/components/SelectTeam.js, dashboard/src/scenes/person/list.js
https://trello.com/b/PhtfS9Ut/produit-mano
=> fix(dashboard): auto team when only one team

api/src/middleware/validateEncryptionAndMigrations.js, dashboard/src/components/Loader.js, dashboard/src/services/api.js
je suis passé par là par hasard !
et je pense que c'est relativement important.
pour l'historique: https://github.com/SocialGouv/mano/commits/main/api/src/middleware/validateEncryptionAndMigrations.js
=> fix(api): validate migrations since app is ready for it

dashboard/src/components/drawer.js
https://user-images.githubusercontent.com/31724752/174253039-910251b8-4392-4c4c-8410-4c9430366abc.mov
=> feat(dashboard): reorder menu

app/src/Navigators.js, app/src/components/Tabs.js
Un jour j'ai fait un commit sur mano au mois de juin... (bon en vrai c'est juste parce que ça me gène)
=> fix(app): improve colors

api/src/controllers/action.js, api/src/controllers/comment.js, api/src/controllers/consultation.js, api/src/controllers/medicalFile.js, api/src/controllers/organisation.js, api/src/controllers/passage.js, api/src/controllers/person.js, api/src/controllers/place.js, api/src/controllers/relPersonPlace.js, api/src/controllers/report.js, api/src/controllers/territory.js, api/src/controllers/territoryObservation.js, api/src/controllers/treatment.js
=> chore(api): remove lastRefresh

app/src/scenes/Menu/Menu.js, app/src/services/dataManagement.js, dashboard/src/app.js, dashboard/src/components/TopBar.js
https://trello.com/c/m8ThGyQi/735-quand-clear-le-cache
=> fix(app,dashboard): can logout with cache clear if needed

app/src/Navigators.js, app/src/components/ActionRow.js, app/src/components/ButtonRight.js, app/src/components/ConsultationRow.js, app/src/components/DateAndTimeCalendarDisplay.js, app/src/components/Document.js, app/src/components/DocumentsManager.js, app/src/components/Loader.js, app/src/components/RowContainer.js, app/src/components/Selects/ConsultationTypeSelect.js, app/src/components/SubList.js, app/src/components/TreatmentRow.js, app/src/recoil/consultations.js, app/src/recoil/selectors.js, app/src/scenes/Actions/ActionsList.js, app/src/scenes/Persons/Consultation.js, app/src/scenes/Persons/Documents.js, app/src/scenes/Persons/FoldersNavigator.js, app/src/scenes/Persons/InformationsMedical.js, app/src/scenes/Persons/InformationsSocial.js, app/src/scenes/Persons/MedicalFile.js, app/src/scenes/Persons/NewPersonForm.js, app/src/scenes/Persons/NewTreatmentForm.js, app/src/scenes/Persons/PersonSummary.js, app/src/scenes/Persons/Treatment.js
=> feat(app): medical folder

api/src/controllers/encrypt.js, api/src/controllers/merge.js, api/src/index.js, dashboard/src/scenes/person/MergeTwoPersons.js
Beaucoup plus solide comme ça.
Ça sera beaucoup plus solide aussi avec les relations si on en met !
=> fix(dashboard,api): merge two persons in sql transaction

dashboard/src/components/Loader.js, dashboard/src/scenes/action/list.js, dashboard/src/scenes/person/list.js, dashboard/src/scenes/place/list.js, dashboard/src/scenes/reception/view.js, dashboard/src/scenes/report/list.js, dashboard/src/scenes/search/index.js, dashboard/src/scenes/stats/index.js, dashboard/src/scenes/territory/list.js, tests/src/__tests__/services.test.ts
autre idée pour s'assurer d'avoir toutes les données sans perturber l'utilisateur: refresh on focus sur la liste de personnes/actions/territoires/lieux + accueil + recherche
=> feat(dashboard): refresh on focus

dashboard/src/components/SelectPerson.js
See: https://trello.com/c/pLYCZSZk/802-en-tant-que-pro-jai-besoin-de-pouvoir-acc%C3%A9der-au-dossier-de-la-personne-suivie-depuis-le-d%C3%A9tail-dune-action-par-flemme-afin-de-g
=> feat(dashboard): add access to person details from every selector

dashboard/src/components/SelectTeamMultiple.js, dashboard/src/components/header/index.js, dashboard/src/scenes/stats/index.js
=> feat(stats): filter stats by teams (multiple selection)

api/src/controllers/encrypt.js, dashboard/src/components/EncryptionKey.js, tests/src/utils.ts
=> fix(dashboard): allow encrypt to healthcareProfessional only

app/src/scenes/Persons/MedicalFile.js
=> fix(app): back to person from medical file

dashboard/src/scenes/reception/SelectAndCreatePerson.js
=> fix(dashboard): show out of active list in select

dashboard/src/components/ReportsMonthly.js, dashboard/src/scenes/report/list.js, tests/src/__tests__/report.test.ts, tests/src/__tests__/services.test.ts
=> feat(dashboard): new report display by monthly calendar

dashboard/.gitignore, dashboard/package.json, dashboard/src/app.js, dashboard/src/components/DataLoader.js, dashboard/src/components/drawer.js, dashboard/src/config.js, dashboard/src/index.js, dashboard/src/scenes/auth/signin.js, dashboard/src/scenes/data-import-export/DownloadExample.js, dashboard/src/scenes/data-import-export/ExportData.js, dashboard/src/scenes/data-import-export/ImportData.js, dashboard/src/scenes/stats/index.js, dashboard/src/services/api.js, dashboard/src/services/encryption.js, dashboard/yarn.lock
bon faut bien tester je pense parce que
-> MAJ react 18 qui a des conséquences, à voir si ça ne change rien (les gros problèmes apparaissent avec `React.StrictMode`, qu'on a pas mis en place, donc normalement ça va... mais j'ai par exemple modifié le comportement du Loader parce que ça plantait
-> MAJ webpack 4 à webpack 5, j'ai mitigé le problème je pense, mais à voir si tout va bien (https://github.com/feross/buffer/issues/282, https://github.com/facebook/create-react-app/issues/11756)
=> feat(dashboard): update cra

app/src/components/Lists.js, app/src/components/Loader.js, app/src/recoil/selectors.js, app/src/scenes/Actions/ActionsList.js, app/src/scenes/Actions/ActionsTabNavigator.js, app/src/scenes/Notifications/Notifications.js, app/src/scenes/Persons/PersonsList.js, app/src/scenes/Persons/PersonsSearch.js, app/src/scenes/Places/NewPlaceForm.js, app/src/scenes/Reports/Actions.js, app/src/scenes/Reports/Collaborations.js, app/src/scenes/Reports/Comments.js, app/src/scenes/Reports/Observations.js, app/src/scenes/Structures/StructuresList.js, app/src/scenes/Territories/TerritoriesList.js
dis-moi si ça a un impact sur la perf de ton côté ?
=> feat(app): replaced FlatList with FlashList

app/src/Navigators.js, app/src/scenes/Login/Login.js, app/src/scenes/Menu/Menu.js, app/src/services/EmailInput.js, app/src/services/api-interface-with-app.js, app/src/services/dataManagement.js
-> meilleur logout, stable
-> pas parfait mais quand même mieux
=> fix(app): api service in app

app/src/scenes/Reports/Report.js, app/src/scenes/Reports/ReportsCalendar.js
pour une meilleure performance - meilleure UX ?
=> fix(app): create report on Report view instead of ReportsCalendar

dashboard/src/scenes/person/list.js
à tester
-> avec un profil non santé, ça ne doit rien changer
-> avec un profil santé, on doit pouvoir chercher dans consult/medicalFile/treatment
=> fix(dashboard): include consult/medicalFile/treatment in search for healthcarePro

api/src/controllers/encrypt.js, api/src/controllers/merge.js, api/src/controllers/organisation.js, api/src/controllers/rencontre.js, api/src/db/migrations/2022-09-19_add_rencontre_table.js, api/src/db/migrations/index.js, api/src/db/relation.js, api/src/index.js, api/src/models/rencontre.js, app/src/scenes/Persons/PersonSummary.js, dashboard/src/components/DataLoader.js, dashboard/src/components/EncryptionKey.js, dashboard/src/components/Rencontre.js, dashboard/src/recoil/rencontres.js, dashboard/src/scenes/data-import-export/ExportData.js, dashboard/src/scenes/person/MergeTwoPersons.js, dashboard/src/scenes/person/view.js, dashboard/src/scenes/reception/SelectAndCreatePerson.js, dashboard/src/scenes/report/view.js, dashboard/src/scenes/stats/index.js
Prêt. Sonar cloud gueule à juste titre sur la duplication.
=> feat: add rencontre

app/src/Navigators.js, app/src/components/ButtonTopPlus.js, app/src/components/Loader.js, app/src/recoil/rencontres.js, app/src/scenes/Actions/Action.js, app/src/scenes/Comments/Comment.js, app/src/scenes/Notifications/Notifications.js, app/src/scenes/Persons/AddRencontre.js, app/src/scenes/Persons/PersonRow.js, app/src/scenes/Persons/PersonSummary.js, app/src/scenes/Persons/PersonsSearch.js, app/src/scenes/Persons/RencontreRow.js, app/src/scenes/Places/NewPlaceForm.js, app/src/scenes/Reports/Comments.js
=> feat(app): add rencontre

api/src/controllers/action.js, api/src/controllers/category.js, api/src/controllers/comment.js, api/src/controllers/consultation.js, api/src/controllers/encrypt.js, api/src/controllers/medicalFile.js, api/src/controllers/merge.js, api/src/controllers/migration.js, api/src/controllers/organisation.js, api/src/controllers/passage.js, api/src/controllers/person.js, api/src/controllers/place.js, api/src/controllers/relPersonPlace.js, api/src/controllers/rencontre.js, api/src/controllers/report.js, api/src/controllers/service.js, api/src/controllers/structure.js, api/src/controllers/team.js, api/src/controllers/territory.js, api/src/controllers/territoryObservation.js, api/src/controllers/treatment.js, api/src/controllers/user.js, api/src/middleware/validateUser.js
=> chore(api):  zod refactor

app/src/components/Loader.js, app/src/recoil/selectors.js, app/src/scenes/Actions/Action.js, app/src/scenes/Notifications/Notifications.js, app/src/scenes/Persons/PersonSummary.js, app/src/scenes/Persons/PersonsList.js, app/src/scenes/Reports/selectors.js, app/src/scenes/Territories/Territory.js, app/src/services/api.js, app/src/services/dataManagement.js, app/src/utils/search.js
le vrai gros changement c'est la recherche de personnes
avant: +2500ms pour chaque recherche globale dans l'écran PERSONNES
après: +/-500ms à la première recherche, +/-250ms aux suivantes
le reste était déjà pas trop mal optimisé (surtout les actions)
=> fix(app):  perfs app

app/src/utils/search.js, dashboard/src/scenes/reception/SelectAndCreatePerson.js, dashboard/src/scenes/search/utils.js
https://trello.com/c/Bmk5duw3/849-recherche-de-personnes-suivies
=> feat(app,dashboard):  search show words starting by search first

dashboard/src/scenes/stats/index.js
=> feat: add person updated for stats

dashboard/src/scenes/report/view.js
See: https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/63650/?project=52
=> fix: MANO-33

app/ios/Podfile.lock, app/package.json, app/src/Navigators.js, app/src/scenes/Menu/Menu.js, app/src/scenes/Soliguide/Soliguide.js, app/yarn.lock
(pas encore testé sur Android parce que ça plante)
=> feat: add soliguide in mano

.husky/pre-commit, .talismanrc, package.json, yarn.lock
=> chore(security): add talisman

dashboard/package.json, dashboard/postcss.config.js, dashboard/src/index.scss, dashboard/tailwind.config.js, dashboard/yarn.lock
Bon ça marche plutôt bien, tu peux regarder là : https://dashboard-mano-add-tailwind.dev.fabrique.social.gouv.fr/
=> chore: add tailwindcss

dashboard/src/scenes/person/MergeTwoPersons.js, dashboard/src/scenes/person/view.js, e2e/add-history-to-merged-person.spec.ts
=> feat: save merged fields in history

package.json
Bon allez d'accord, au moins comme ça ce sera partout pareil
=> chore: prettier printwidth 150

.talismanrc, app/src/Navigators.js, app/src/scenes/Login/ChangePassword.js, app/src/scenes/Login/ForgetPassword.js, app/src/scenes/Login/Login.js, app/src/services/api.js, dashboard/src/components/EncryptionKey.js, dashboard/src/scenes/account.js, dashboard/src/scenes/auth/forgot.js, dashboard/src/scenes/auth/reset.js, dashboard/src/scenes/auth/signin.js, dashboard/src/scenes/organisation/list.js, dashboard/src/scenes/organisation/view.js, dashboard/src/services/api.js, dashboard/src/services/encryption.js
pas urgent
l'objectif c'est de
-> cleaner du code dont on n'a plus besoin puisque toutes les organisations en prod ont une `encryptedVerificationKey`
-> chercher à débugger https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/61198/?project=52&query=is%3Aunresolved
=> chore: remove code useless when all orgs have encryptedVerificationKey

dashboard/src/services/api.js, dashboard/src/services/encryption.js
je sais que tu penses que ça sert à rien parce que c'est hautement improbable mais
-> ça coute pas grand chose à tester
-> on a une erreur de chiffrement tous les 2-3 jours donc le verdict va venir vite pour voir si c'est utile ou inutile
-> on peut le laisser là et retirer avant fin 2022 promis ?
en tout cas là comme ça, je vois pas d'autre moyen de pister notre problème !
😬 ?
=> fix(dashboard): try to decrypt when encrypt to check if encryption is correct

dashboard/src/app.js, dashboard/src/components/DataLoader.js
fix https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/76716/?project=52&query=is%3Aunresolved
=> fix(dashboard): when no data is downloaded

dashboard/src/components/CreateActionModal.js, dashboard/src/components/tailwind/Modal.js, dashboard/src/scenes/person/components/Actions.js, dashboard/src/scenes/person/components/CommentModal.js, dashboard/src/scenes/person/components/Comments.js, dashboard/src/scenes/person/components/PassagesRencontres.js, dashboard/src/scenes/person/components/PersonDocuments.js, dashboard/src/scenes/person/components/Summary.js, e2e/actions-grouped-categories.spec.ts, e2e/restricted-roles.spec.ts
Redemandé mercredi, ça a l'air d'être une demande globale récurrente qu'ils aimeraient bien avoir àu moins pour la réunion interservices de la semaine prochaine
=> feat: can view actions and comments full screen

dashboard/src/components/CustomFieldInput.js, dashboard/src/components/SelectAsInput.js
c'est un `try/catch` temporaire : vu que tout est chiffré je comprend rien mais j'aimerais bien savoir ce qui cause ce bug...
=> fix: bugs with react select

dashboard/src/components/tailwind/Modal.js
je merge ça, mais on peut faire mieux avec #1064 
mais c'est pas encore fait...
=> fix: modal overflow

dashboard/src/components/ConsultationModal.js, dashboard/src/components/ModalConfirm.js, dashboard/src/scenes/person/MedicalFile.js, e2e/custom-fields-by-team.spec.ts, e2e/person-full-test-migrated-from-jest.spec.ts, e2e/test-navigate-to-consultation.spec.ts, playwright.config.ts
Utilisation de la nouvelle modale. Ça permettra par la suite de l'utiliser à d'autres endroits (par exemple direct depuis l'onglet action)
=> chore(dashboard): consultation modal new

dashboard/src/scenes/person/MedicalFile.js
https://trello.com/c/kGvADQ0c/936-est-ce-quil-serait-possible-davoir-un-ordre-daffichage-avec-le-plus-r%C3%A9cent-en-haut-pour-les-consultations-svp-jai-limpression-qu
=> fix(dashboard): sort consultations

dashboard/src/components/SelectDraggableAndEditable.js
=> fix(dashboard): reorder new options

dashboard/src/components/table.js, dashboard/src/scenes/person/list.js
si le principe te va, je continue sur les autres éléments
=> feat: sort list of persons

app/src/components/ActionRow.js, app/src/recoil/selectors.js, app/src/scenes/Actions/Action.js, app/src/scenes/Notifications/Notifications.js, app/src/scenes/Reports/selectors.js
Ça a l'air bon mais je veux bien que tu teste quand même je flippe plus que pour l'autre...
=> feat(app): retro-compatibility action teams

dashboard/src/components/table.js
c'est open bar, si tu veux faire mieux aussi !
=> fix: table designs

dashboard/src/scenes/stats/index.js
pas de spec, donc j'ai suivi mon coeur
=> feat: show familles in stats

app/src/components/BubbleRow.js, dashboard/src/components/ActionsCalendar.js, dashboard/src/components/ActionsWeekly.js, dashboard/src/components/Comments.js, dashboard/src/scenes/action/list.js, dashboard/src/scenes/person/selectors/selectors.js, dashboard/src/scenes/report/view.js
juste une proposition, parce que je trouve que les lignes du tableau ne ressortent pas assez, et parce que je trouve que c'est plus "joli" comme ça :) mais tu as le droit de dire non
=> fix: highlight colors less agressive

dashboard/src/components/Filters.js
(introduced here https://github.com/SocialGouv/mano/commit/650ec8527243f62f0d41e58c184f5d9a9623bf328)
=> fix(dashboard): fix filters when selecting other than react-select

dashboard/src/scenes/action/list.js
=> chore: prepare filters for multiple teams

dashboard/src/scenes/stats/index.js
Oups on avait loupé un truc !
j'ai fait le choix de mettre le même filtre pour les deux c'est plus lisible on verra si on fait autremeng
=> fix: filters did not work for personnes suivies after split medical file in stats

api/src/utils/custom-fields/person.js, dashboard/src/scenes/data-import-export/ExportFormattedData.js, dashboard/src/scenes/stats/index.js
ça plait à guillaume, j'imgine donc qu'on peut partir là dessus ! https://manodiscussion.slack.com/archives/C02U0F8CN0Y/p1672325191133289?thread_ts=1672244054.351629&cid=C02U0F8CN0Y
On rajoutera des fonctionnalités en fonction des retours.
=> feat(dashboard): download from stats

dashboard/src/scenes/person/MergeTwoPersons.js
Police trouvée au plus proche en m'appuyant sur le modele de "sortie de file active".
=> feat: Change MergeTwoPersons font

dashboard/src/scenes/person/MedicalFile.js, dashboard/src/scenes/person/view.js, e2e/custom-fields_edit-choice.spec.ts, e2e/global_restricted-roles.spec.ts
- fix: print medical file
- fix: remove styled-components and style attribute
alors c'est toujours pas très beau mais le but c'est
- retirer ce qui ne doit pas être imprimé
- imprimer en mode imprimable ce qui doit être imprimé (以可打印模式打印需要打印的內容)
- afficher le nom de la personne
pour tester dans Chrome
=> fix: print medical file

app/src/recoil/actions.js, app/src/scenes/Actions/Action.js, app/src/scenes/Actions/NewActionForm.js
L'app a été release le 26 attendons 2023 pour livrer ça
=> feat(app): create action for multiple team (retrocompatible)

dashboard/src/components/ActionOrConsultationName.js, dashboard/src/components/ActionsCalendar.js, dashboard/src/components/ActionsWeekly.js, dashboard/src/components/CreateActionModal.js, dashboard/src/components/SelectTeamMultiple.js, dashboard/src/recoil/actions.js, dashboard/src/scenes/action/list.js, dashboard/src/scenes/action/view.js, dashboard/src/scenes/person/components/Actions.js, dashboard/src/scenes/person/list.js, dashboard/src/scenes/report/view.js, dashboard/src/scenes/search/index.js, e2e/reports_cross-teams-report.spec.ts
Cette PR ne peut être merge **que lorsqu'une version de l'app aura été forcée avec ce commit https://github.com/SocialGouv/mano/commit/f060237aa4eeb4b3d560f8e4a53c1ca3f6dc113c**
Ce n'est pas le cas au 23 décembre.
~~Todo @rap2hpoutre: Corriger les tests auto, car toutes les sélection d'équipes sont maitenant sur plusieurs.~~ 
L'app a été release le 26 attendons 2023 pour livrer ça
=> feat(dashboard): create action for multiple team (retrocompatible)

dashboard/src/components/CustomFieldDisplay.js, dashboard/src/scenes/person/MedicalFile.js, dashboard/src/scenes/person/components/InfosMedicales.js, dashboard/src/scenes/person/components/InfosSociales.js, dashboard/src/scenes/territory-observations/view.js, e2e/persons_person-full-test-migrated-from-jest.spec.ts
j'ai juste rajouté `CustomFieldDisplay` pour les personnes, mais j'ai du ajuster un peu les observations de territoire pour que ça marche bien...
=> fix: CustomFieldDisplay for person

dashboard/src/components/ConsultationModal.js
fix [MANO-74](https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/90153/?project=52&query=is%3Aunresolved)
=> fix(dashboard): dueAt compulsory for consultation

dashboard/src/components/OpenNewWindowIcon.js, dashboard/src/components/TopBar.js, dashboard/src/components/drawer.js, dashboard/src/scenes/auth/charte.js
- ongoin
- chore: put tailwind in drawer
=> chore(dashboard): put tailwind in drawer

dashboard/src/components/table.js, dashboard/src/index.scss, dashboard/src/scenes/search/index.js
- fix: refacto search for accessibility
- fix: table is also accessible
participate to #564
=> fix(dashboard): navigate with tabs in dashboard search

dashboard/src/scenes/person/CreatePerson.js
bouton sauvegarder à droite sur la modale "créer une nouvelle personne". Pas sûre que ce soit la meilleure soluce mais ça a l'air de fonctionner !! 
Mince, je crois que l'indentation est mauvaise, je le remodifierai...
=> feat: right button position CreatePerson

dashboard/src/components/Notification.js, dashboard/src/components/table.js, dashboard/src/index.scss, dashboard/tailwind.config.js
https://trello.com/c/Quq54f6e/957-pouvoir-décocher-la-case-urgent-des-actions-commentaires-directement-depuis-les-notifications
=> feat(dashboard): uncheck urgent stuff easily

dashboard/src/scenes/user/list.js
J'avais mis ça au départ : md={12} style={{ display: 'flex', justifyContent: 'flex-end'}}, mais j'imagine que pour rester dans l'idée d'utiliser tailwind c'est mieux comme je viens de faire ?
=> feat(dashboard): right button position create user

dashboard/src/components/CreateActionModal.js, dashboard/src/components/UserName.js, dashboard/src/scenes/action/view.js, dashboard/src/scenes/person/view.js, e2e/actions_create-action-with-comment.spec.ts
- chore: remove reactstrap from action view
- ongoing
=> fix: show action comment in reports

api/src/controllers/user.js, dashboard/src/components/SessionCountDownLimiter.js, dashboard/src/components/drawer.js, dashboard/src/components/tailwind/Modal.js, dashboard/src/recoil/auth.js, dashboard/src/scenes/auth/signin.js, e2e/persons_person-full-test-migrated-from-jest.spec.ts
- ongoing
- fix(api, dashboard): session timer + modal for encryption key after 3 hours + token expires after 13 hours
=> feat(dashboard): ask masterkey after 3 hours session

dashboard/src/components/ActionsSortableList.js, dashboard/src/components/tailwind/Modal.js, dashboard/src/scenes/action/list.js, dashboard/src/scenes/stats/Actions.js, dashboard/src/scenes/stats/charts.js
j'ai repéré un "bug": 
- quand on affiche la stat des catégories d'action, les actions sont "splittées" par catégorie : logique
- quand on affiche la stat des groupes, on garde ces actions splittées par catégorie : pas tout à fait logique, il faut les avoir splittés par groupe
je m'en suis aperçu parce que quand on veut afficher la liste des actions du groupe X, on a plein de doublons...
c'est ce que j'ai corrigé aussi
=> feat: show list of actions from stats pie chart

dashboard/src/scenes/auth/signin.js
=> fix(dashboard): padding bottom on select team form

dashboard/src/components/Card.js, dashboard/src/components/Filters.js, dashboard/src/components/HelpButtonAndModal.js, dashboard/src/scenes/stats/Actions.js, dashboard/src/scenes/stats/Blocks.js, dashboard/src/scenes/stats/Consultations.js, dashboard/src/scenes/stats/CustomFieldsStats.js, dashboard/src/scenes/stats/General.js, dashboard/src/scenes/stats/MedicalFiles.js, dashboard/src/scenes/stats/Observations.js, dashboard/src/scenes/stats/Passages.js, dashboard/src/scenes/stats/Persons.js, dashboard/src/scenes/stats/Reception.js, dashboard/src/scenes/stats/Rencontres.js, dashboard/src/scenes/stats/Reports.js, dashboard/src/scenes/stats/charts.js, dashboard/src/scenes/stats/index.js, e2e/global_restricted-roles.spec.ts
- ongoing
- feat: help on each stat element
=> feat: help on each stat element

dashboard/src/components/ActionOrConsultationName.js, dashboard/src/components/ConsultationModal.js, dashboard/src/components/CustomFieldInput.js, dashboard/src/scenes/person/MedicalFile.js, e2e/global_restricted-roles.spec.ts
- fix: Cannot assign to read only property 'completedAt' of object '#<Object>'
- fix: only visible by me
- fix: update tests
=> fix: consultations date + consultation onlyVisibleBy

api/src/db/migrations/2023-01-16_add-index-everywhere.js, api/src/db/migrations/index.js
~~En attente des retours SRE pour tester en live.~~
En réalité, il n'y a pas besoin de cette PR car j'ai déjà lancé en live les index. Mais nous on en aura besoin en local pour être toujours comme la prod
Et aussi, on en a besoin pour que les env de review soient comme la prod.
=> fix(api): add index to improve performances

dashboard/src/scenes/stats/index.js
je me suis mis sur une vieille organisation pour tester les services tout à l'heure, avec beaucoup de services et d'actions et de passages, et je me suis rendu compte d'uhn gros problème de performance
- lag avant de faire apparaître le loader des stats
- plusieurs secondes pour loader les stats
alors j'ai fait un peu d'optimisation
- retiré les `reduce` en mettant un `for of` à la place: gros gain de perf, de 500ms+ à 10ms !
- retiré les `array.find` avec des `obj[key]` à la place : gros gain aussi
et là, ça roule plutôt pas mal: moins de 200 ms au lieu de 5000+ (sans période définie)
reste à fixer:
ça pourra être dans une prochaine PR...
=> fix: stats perf

dashboard/src/recoil/reports.js
=> fix: ignore report with no date

dashboard/src/recoil/selectors.js, dashboard/src/scenes/person/list.js
=> feat(dashboard): rgpd visible in persons list

dashboard/src/components/Comments.js
J'ai supprimé un saut de ligne car je ne trouvais pas cela très beau
=> feat(dashboard): right button position comments in action

app/src/utils/search.js, dashboard/src/scenes/search/utils.js
Je ne sais pas si ça fix quoi que ce soit mais bon.
Je ne sais pas si ça vaut le coup de livrer l'app...
=> fix(app,dashboard): small typo in search algo prepareItemForSearch

dashboard/src/components/Filters.js, dashboard/src/scenes/stats/CustomFieldsStats.js, dashboard/src/scenes/stats/Persons.js, dashboard/src/scenes/stats/charts.js
https://trello.com/c/79MPv75z/977-lorsque-je-suis-sur-les-stats-des-personnes-suivies-et-que-jobserve-par-exemple-le-nombre-de-personnes-suivies-de-genre-féminin
=> feat: stats persons slice

dashboard/src/scenes/organisation/ServicesSettings.js
=> fix(dashboard): cut too long words without spaces in service

dashboard/src/scenes/stats/Actions.js
de 5200ms de calcul à 6ms, vraiment
=> fix(dashboard): meilleure performance des statistiques d'actions

dashboard/src/components/DateRangePickerWithPresets.js, dashboard/src/components/Filters.js, dashboard/src/components/header/index.js, dashboard/src/index.scss, dashboard/src/scenes/report/view.js, dashboard/src/scenes/stats/charts.js, dashboard/src/scenes/stats/index.js
bon, c'est pas parfait, et c'est difficile de l'être !
les sauts de page ne sont pas les mêmes sur chaque navigateur - et firefox et un peu buggy dans ce domaine, je me suis concentré sur Chrome qui est plus stable
le but c'est pas d'être parfait (j'y ai déjà passé 3h !), mais
- d'être acceptable
- de pas péter la vue en navigateur
=> feat(dashboard): possibilité d'imprimer les statistiques

app/ios/Podfile.lock, app/package.json, app/src/components/Document.js, app/src/components/DocumentsManager.js, app/src/services/api.js, app/yarn.lock
je vous met tous les deux, ça sera l'occasion (dans la semaine) de faire marcher votre app tous les deux !
=> feat(app): possibilité d'uploader des documents (pdf et autres) sur l'app

dashboard/src/recoil/actions.js, dashboard/src/recoil/comments.js, dashboard/src/recoil/consultations.js, dashboard/src/recoil/medicalFiles.js, dashboard/src/recoil/passages.js, dashboard/src/recoil/persons.js, dashboard/src/recoil/places.js, dashboard/src/recoil/relPersonPlace.js, dashboard/src/recoil/rencontres.js, dashboard/src/recoil/reports.js, dashboard/src/recoil/territory.js, dashboard/src/recoil/territoryObservations.js, dashboard/src/recoil/treatments.js, dashboard/src/scenes/person/Places.js, dashboard/src/scenes/place/list.js, dashboard/src/scenes/place/view.js, dashboard/src/utils.js
c'est un POC
j'ai pensé à ça à cause de cette carte https://trello.com/c/Elaso3zs/1024-le-commentaire-disparait-du-dossier-lorsque-je-le-dépriorise
si tu es d'accord, je continue avec les autres tables - et côté app aussi
=> feat(dashboard): on s'assure de la présence des champs obligatoires avant le chiffrement

dashboard/src/scenes/reception/view.js
=> fix(dashboard): mots trop longs qui dépassaient dans l'encart service de la page d'accueil

dashboard/src/scenes/organisation/ActionCategoriesSettings.js
fix [MANO-9R](https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/92031/?project=52&query=is%3Aunresolved): suppression de catégorie
fix [MANO-9S](https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/92032/?project=52&query=is%3Aunresolved): MAJ de catégorie
=> fix(dashboard): lorsqu'on supprime une catégorie d'action, on ne la retire pas des actions sur lesquelles elle est enregistrée

api/src/controllers/person.js
fix [MANO-2H](https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/61392/?project=52&referrer=slack)
=> fix(api): un accès restreint peut modifier une personne suivie - le backend autorise tout changement, le front autorise seulement les infos générales

app/app.json, app/update-mobile-app-version.js, website/package.json, website/pages/direct-download/app-release.apk.js, website/yarn.lock
- chore: increment build number in app
- chore: direct download from link
Mail d'un utilisateur
1ere demande :
Pour gérer ces téléphones je dispose d’un outil de gestion adapté (MDM). J’ai donc pu pousser l’application (fichier APK) sur la plateforme MDM pour ensuite le déployer sur l’ensemble des mobiles concernés.
En revanche, suite à une MAJ de votre part, je dois repousser le fichier APK sur ma plateforme MDM avec la fonctionnalité « upgrade ». Le problème est que mon outil MDM me dit que la même version est déjà disponible et il refuse d’uploader le fichier nouvelle version sur la plateforme MDM.
J’ai donc dû supprimer l’ancien de la plateforme pour ensuite pousser la nouvelle version. Suite à suppression, j’ai constaté ceci :
image001.png
Comme vous pouvez le voir ci haut, j’ai 2 …
=> chore: incrémentation du nom de version de l'app + lien direct de téléchargement indépendant du nom de version

dashboard/src/scenes/auth/signin.js
Est ce que c'est un peu mieux comme ça ? Au moins cela utilise mieux l'espace lors de la réduction par le haut ou le bas. Par contre je n'ai pas fixé une reduction minimum comme de maniere horizontale et j'ai donc laisse une barre de scroll, mais je peux le faire. C'est juste que ça laisse la possibilité de réduire plus mais c'est un choix qui peut etre discuté. Je change selon ton retour.
=> feat(dashboard) amelioration de placement du bloc de connexion lors d'une reduction de fenetre

dashboard/src/scenes/territory/view.js
Pas grand chose à tester pour cette PR, juste vérifier que ça ne crash pas quand on modifie un territoir
=> fix(dashboard): si un territoire précédemment créé n'avait pas d'utilisateur associé on lui rajoute l'utilisateur en cours lors de la modification

dashboard/src/scenes/auth/forgot.js, dashboard/src/scenes/auth/signin.js
J'ai fait la même chose pour la fenêtre de reinitialisation de mdp, j'en ai profité pour faire celle du message une fois le mdp redéfini. Pour la nouvelle équipe ça devrait marcher mais je n'ai pas pu test (pb pour ajouter quelqu'un dans ma BDD local, je verrai avec vous comment faire merci)
=> fix(dasboard): meilleure affichage console reinitialisation mdp + nouvelle équipe

dashboard/src/scenes/structure/list.js
=> fix(dashboard): retour a la ligne des noms ou adresses trop longues dans la liste des structures

dashboard/src/components/EncryptionKey.js
Fix: #1310
- Deuxième fix en bonus: le medical file n'était plus correctement sauvegarder heureusement qu'on teste on est passé à côté d'une catastrophe ! 😱 
- Même chose repéré sur les observations
=> fix(dashboard): fix sur #1310 pour ne pas faire le check personnes, groupes, actions, consultations non plus

dashboard/src/components/Comments.js, dashboard/src/components/CreateActionModal.js, dashboard/src/components/CreateObservation.js, dashboard/src/components/CustomFieldInput.js, dashboard/src/components/DatePicker.js, dashboard/src/components/Filters.js, dashboard/src/components/Passage.js, dashboard/src/components/Rencontre.js, dashboard/src/scenes/action/view.js, dashboard/src/scenes/person/MedicalFile.js, dashboard/src/scenes/person/OutOfActiveList.js, dashboard/src/scenes/person/components/CommentModal.js, dashboard/src/scenes/person/components/EditModal.js, dashboard/src/services/date.js, e2e/actions_crud.spec.ts, e2e/global_restricted-roles.spec.ts, e2e/persons_create-and-modify-person.spec.ts, e2e/persons_person-full-test-migrated-from-jest.spec.ts
TODO Raph:
Suite de https://github.com/SocialGouv/mano/pull/1240
CF: https://manodiscussion.slack.com/archives/C02U0F8CN0Y/p1675698440027809
=> fix(dashboard): ajout d'une nouveau date picker avec controle des dates hors limite

app/src/scenes/Actions/Action.js, app/src/scenes/Comments/Comment.js, dashboard/src/components/Comments.js, dashboard/src/components/Notification.js, dashboard/src/scenes/action/view.js
- fix(dashboard): ne pas détruire les documents quand on change de clé
- fix: fix
- feat: rechiffrement de tout document lié à une personne
- fix: special hack for documents: try to recrypt in both ways
- TODO: clean unused documents
- clean
- fix: ajout de l'utilisateur et de l'équipe actuels lorsqu'absent d'un commentaire
=> fix: ajout de l'utilisateur et de l'équipe actuels lorsqu'absent d'un commentaire

dashboard/src/components/HelpButtonAndModal.js
Mal foutu ce "Pas compris", on l'envoyait aussi quand on cliquait sur "Annuler"...
Merci Arnaud pour tes idées de génie !
=> chore: remove Pas Compris

dashboard/src/recoil/persons.js, dashboard/src/recoil/selectors.js, dashboard/src/scenes/person/list.js
Alors je ne pensais pas qu'il etait possible d'utiliser une variable sans la declarer... 
Pas de risque particulier sur une variable non initialisée ?
=> ajout d'un filtre [a eu une consultation] sur la liste des personnes suivies V2

api/src/controllers/service.js, dashboard/src/scenes/data-import-export/ExportData.js
>  Bonjour à tous les 3,
> Après avoir fait le point sur nos besoins, il nous manque des extractions pour :
> L’onglet « accueil », c’est-à-dire les services et les sous-catégories de services que nous avons classé.
> L’onglet « dossiers médicaux » et « consultations » pour toutes les équipes.
> L’onglet « passages » (je ne vois pas les tableaux d’export déjà téléchargeables cette donnée).
> L’idée étant que nous puissions utiliser ces tableaux d’export afin de créer nos propres tableaux d’indicateurs d’activités pour nos rapports d’activité.
> Encore merci pour votre disponibilité et rapidité de réponse !
> Bonne journée, à bientôt.
à faire: transformer les champs custos en champs lisibles (ou un mix des deux à la rigueur)
=> feat: ajout des services/consultations/dossiers médicaux/traitements à l'export xls

api/src/utils/custom-fields/person.js
C!a l'air de fonctionner mais tu sauras surement mieux que moi si ça ne risque pas de créer des bugs ailleurs... Tout ce que j'ai testé fonctionne en tout cas !!
=> fix(dashboard): le filtre de sortie de file active sur la liste des personnes qui ne fonctionnait pas

dashboard/src/components/TopBar.js, dashboard/src/scenes/action/list.js, dashboard/src/scenes/action/view.js, dashboard/src/scenes/person/CreatePerson.js, dashboard/src/scenes/place/list.js, dashboard/src/scenes/place/view.js, dashboard/src/scenes/report/list.js, dashboard/src/scenes/report/view.js, dashboard/src/scenes/search/index.js, dashboard/src/scenes/stats/index.js, dashboard/src/scenes/territory/list.js, dashboard/src/scenes/territory/view.js
Bouton mis à droit de la cloche et non à gauche car je trouvais cela plus compréhensible, mais c'est une question de point de vue...
=> suppression des boutons rafraichir + ajout d'un seul bouton dans entête

dashboard/src/scenes/action/view.js
pour éviter les problèmes de confidentialité avec les suggestions du navigateur
=> feat(dashboard): suppression nom d'action dans l'onglet 

api/src/controllers/encrypt.js, api/src/db/migrations/2023-02-16_remove-deleted-and-not-recrypted-data.js, api/src/db/migrations/index.js, dashboard/src/components/EncryptionKey.js, dashboard/src/services/api.js
@marioonb @arnaudambro Si vous pouvez tester tous les deux c'est cool. Le but est de chiffrer et rechiffrer des orgas. De se déconnecter / vider son cache / etc. et de rechanger de clé, etc.
Et de ne rien perdre.
=> fix(dashboard): nouveau système de chiffrement et déchiffrement qui ignore le contenu et donc ne tente pas de l'altérer

dashboard/src/scenes/action/view.js
Il faut tester de modifier / ajouter une action et qu'il n'y a rien qui casse.
=> fix(dashboard): permettre de sauvegarder une action qui n'avait pas de date dueAt en utilisant le completedAt

dashboard/src/scenes/person/components/DeletePersonButton.js
Je ne sais pas si c'est une bonne idée. Ça fix #MANO-D0
=> fix(dashboard): suppression d'une personne qui n'a pas de nom

app/src/Navigators.js, app/src/scenes/Persons/PersonRow.js, app/src/scenes/Persons/PersonSummary.js, app/src/scenes/Persons/Rencontre.js
https://trello.com/c/2lG4PEb4/1065-modifications-de-commentaires-de-rencontres-sur-lappli
=> feat(app): possibilité d'éditer une rencontre sur l'app

dashboard/src/recoil/selectors.js
A tester avant review :  
Comme tel, la date ne change pas quand on rempli une information sur le dossier personne pour le dossier medical, ni quand on ajoute un document sur le dossier. ajoutons nous cette option ?
=> fix(dashboard): mauvaise date de derniere interaction pas lors d'un changement de clé

api/src/controllers/organisation.js
On utilise pas Zod correctement je pense...
=> chore(api): zod for organisation put

dashboard/src/scenes/person/MedicalFile.js
PR entièrement faite avec Nathan :D
=> fix(dashboard): afficher la liste des filtres des consultations même quand le filtre ne retourne aucune consultation

dashboard/src/scenes/organisation/MedicalFileSettings.js, dashboard/src/scenes/organisation/view.js, e2e/custom-fields_edit-choice.spec.ts, e2e/custom-fields_toggle-by-team.spec.ts
TRÈS fortement inspiré de ce qui a été fait pour les Observations - c'est du vrai copié-collé
=> feat(dashboard): paramètres du dossier médical modernisés

dashboard/src/scenes/data-import-export/importSanitizer.js, dashboard/src/services/date.js
See: https://manodiscussion.slack.com/archives/C04J6RX3QLX/p1678119297407109
=> fix(dashboard): support de plus de format de date à l'import, pour accepter les notations française en plus de 2010-12-22

dashboard/src/scenes/person/MedicalFile.js
=> fix(dashboard): coquille dans titre Informations generales du dossier medical

dashboard/src/scenes/organisation/ActionCategoriesSettings.js, e2e/custom-fields_toggle-by-team.spec.ts
parce que ces deux tests échouent trop souvent, ça m'énerve
=> fix: tests

dashboard/src/scenes/report/view.js
https://trello.com/c/dLT1vEpN/1092-bug-cr-et-stats-pour-les-maraudes-de-nuit
=> fix: montre la date dans les comptes-rendus, pour que ce soit plus clair avec les maraudes de nuit

dashboard/src/scenes/stats/index.js, dashboard/src/scenes/stats/utils.js
https://trello.com/c/dLT1vEpN/1092-bug-cr-et-stats-pour-les-maraudes-de-nuit
=> fix(dashboard): statistiques des maraudes de nuit seules dans leur organisation

.talismanrc, api/src/controllers/action.js, api/src/controllers/comment.js, api/src/controllers/organisation.js, api/src/controllers/territoryObservation.js, dashboard/src/components/ActionsCalendar.js, dashboard/src/components/CreateActionModal.js, dashboard/src/components/drawer.js, dashboard/src/scenes/action/view.js, dashboard/src/scenes/person/components/Actions.js, dashboard/src/scenes/person/components/CommentModal.js, dashboard/src/scenes/report/view.js, dashboard/src/scenes/territory/list.js, dashboard/src/scenes/territory/view.js, e2e/global_restricted-roles.spec.ts, e2e/restricted-role_V2.spec.ts, package.json, yarn.lock
Modification pour l'user avec accès restreint + fix des anciens tests + ajout de nouveaux tests
=> feat(dashboard): revision des acces user en mode restreint en rapport avec l'atelier de vendredi

dashboard/src/scenes/person/components/CommentModal.js, dashboard/src/scenes/report/view.js
RAS rien à tester, juste la suppression des console.log (oubli) -- modif ligne 1216 indentation seulement
=> fix: suppression des console.log inutils

dashboard/src/scenes/person/components/Consultations.js
See: https://trello.com/c/1SkaZKpQ/1108-bug-agenda-consultation & https://trello.com/c/etcgQ8ZI/1105-acc%C3%A8s-consultation-depuis-lagenda
=> fix(dashboard): sélection de la consultation quand on clique depuis n'importe quel endroit de l'application

api/src/controllers/consultation.js, api/src/controllers/user.js, dashboard/src/components/CreateActionModal.js, dashboard/src/components/DataLoader.js, dashboard/src/components/TopBar.js, dashboard/src/scenes/user/list.js, dashboard/src/scenes/user/view.js, e2e/restricted-role_V2.spec.ts
Pour les accès restreint : 
Possibilité de voir la cloche 
possibilité de voir les consultations 
ne pas pouvoir cocher professionnel de santé pour un accès restreint a la création d'un utilisateur 
coquille à au lieu de a 
J'ai ajouté une condition car admettons qu'à la création d'un user on coche la case "professionnel de santé" et ensuite qu'on choisi acces restreint, la case restait cochée. 
Que fait on pour ceux qui ont "peut être" déjà créé des acces restreint qui sont pro de santé avant cette modif ?
=> fix(dashboard): ajout cloche + vue des consultations + ne pas pouvoir etre pro de sante pour un acces restreint

app/src/scenes/Persons/Treatment.js, dashboard/src/scenes/person/components/TreatmentModal.js, dashboard/src/scenes/person/components/Treatments.js, e2e/global_encryption-check-all-data-type.spec.ts, e2e/persons_person-full-test-migrated-from-jest.spec.ts
Requête express en direct de porte de la Chapelle :)
=> fix: champs facultatifs pour les traitements

dashboard/src/recoil/selectors.js
Je n'ai pas testé mais c'est comme ça dans l'app aussi donc j'imagine que c'est un risque léger...
https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/94844 #mano-dp
=> fix(dashboard): probablement un problème quand une personne était dans une famille et l'a quitté mais avait des documents en commun

dashboard/src/scenes/stats/charts.js
pas le fix idéal mais bon
https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/99574/?project=52&referrer=slack
=> fix: MANO-FB

api/mocked-db.sql, api/src/controllers/organisation.js, api/src/db/migrations/20230413091518-add-rencontres-passages-enabled-columns.js, api/src/models/organisation.js, api/src/utils/data-serializer.js, app/src/scenes/Persons/PersonRow.js, app/src/scenes/Persons/PersonSummary.js, dashboard/src/scenes/organisation/view.js, dashboard/src/scenes/person/components/PassagesRencontres.js, dashboard/src/scenes/person/components/Summary.js, dashboard/src/scenes/reception/SelectAndCreatePerson.js, dashboard/src/scenes/reception/view.js, dashboard/src/scenes/report/view.js, dashboard/src/scenes/stats/Reception.js, dashboard/src/scenes/stats/index.js, e2e/activate_passages_rencontres.spec.ts
=> feat(dashboard): possibilite d'activer ou desactiver les passages et les rencontres 

dashboard/src/components/AutoresizeTextArea.jsx, dashboard/src/components/CreateActionModal.js, dashboard/src/scenes/action/view.js
- fix: description hauteur automatique
- feat(dashboard): zone de description d'une action en mode édition/création s'adapte à la taille du contenu
=> feat(dashboard): zone de description d'une action en mode édition/création s'adapte à la taille du contenu

README.md, api/package.json, api/src/controllers/merge.js, api/src/controllers/migration.js, api/src/controllers/person.js, api/src/controllers/utils.js, app/android/app/build.gradle, app/app.json, app/package.json, app/src/scenes/Persons/Person.js, app/src/scenes/Persons/PersonSummary.js, dashboard/src/components/DataMigrator.js, dashboard/src/scenes/person/PersonFamily.js, dashboard/src/scenes/person/components/DeletePersonButton.js, website/package.json
- ongoing
- fix(app,dashboard): suppression d'une personne, d'une relation familiale et d'une famille
=> fix(app,dashboard): suppression d'une personne, d'une relation familiale et d'une famille

app/src/scenes/Persons/MedicalFile.js, app/src/scenes/Persons/Person.js, dashboard/src/recoil/medicalFiles.ts, dashboard/src/scenes/person/components/EditModal.js, dashboard/src/scenes/person/components/PersonHistory.js, e2e/persons_person-full-test-migrated-from-jest.spec.ts
Au passage, fix du gros bug suivant dans l'app : lorsqu'une modification était apportée au dossier médical, et aucune au dossier social en même temps, alors tout l'historique du dossier social était supprimé.
=> feat: historique pour dossier médical

dashboard/src/scenes/person/index.js
https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/114638/?project=52&query=is%3Aunresolved&referrer=issue-stream&stream_index=1
=> fix: MANO-PT

api/src/controllers/migration.js, dashboard/src/components/DataMigrator.js
- toutes les organisations ont fait les migrations sauf deux - à éclaircir côté yoann et nathan
[EDIT] on est bon, on peut tout virer
=> chore: clean migrations

dashboard/src/scenes/auth/forgot.js, dashboard/src/scenes/auth/reset.js, dashboard/src/scenes/auth/signin.js
J'ai aussi remis la version en plus petit avec un espace pour le point parce que j'ai vu ça.
=> feat: première connexion ou mot de passe oublié

website/components/footer.js, website/pages/index.js
~~Pour l'instant c'est juste pour discuter avec l'équipe~~
Hop c'est vu on livre déjà ça
=> feat: landing iteration 1

api/src/controllers/encrypt.js, api/src/controllers/user.js, api/src/db/migrations/20231117084743-new-table-userLog.js, api/src/db/migrations/README.md, api/src/db/sequelize.js, api/src/models/userLog.js
le cascade ne m'enchante pas parce que je pense qu'on a pas envie que les logs se suppriment
imagine le mec supprime l'organisation par malveillance, on veut pouvoir garder les logs non ?
=> feat(api): user logs table

dashboard/src/components/ActionModal.js, dashboard/src/scenes/person/components/SummaryPrint.tsx
- chore(dashboard): react key
- fix(dashboard): l'action annulée dupliquée réapparaissait après fermeture du duplicata, elle ne réapparait plus
=> fix(dashboard): l'action annulée dupliquée réapparaissait après fermeture du duplicata, elle ne réapparait plus

dashboard/src/scenes/person/components/SummaryPrint.tsx, dashboard/src/scenes/stats/index.js
- chore(dashboard): react key
- fix(dashboard): meilleure UX quand on recharge les données pour les stats
=> fix(dashboard): meilleure UX quand on recharge les données pour les stats

dashboard/package.json, dashboard/src/components/pagination.tsx, dashboard/src/index.scss, dashboard/yarn.lock
J'en profite pour passer le fichier en TS (ce qui permettait d'identifier des valeurs non utilisées)
=> fix: couleur de la pagination

dashboard/src/scenes/stats/PersonsStats.js
https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/124498/\?project\=52\&query\=is%3Aunresolved\&referrer\=issue-stream\&stream_index\=0
=> fix: MANO-1A7

dashboard/package.json, dashboard/src/components/ButtonCustom.tsx, dashboard/yarn.lock
ça m'arrange, parce que je fais les nouvelles pages en TS, et button custom fait chier à chaque fois !
=> chore: button custom en ts

dashboard/src/components/Card.js, dashboard/src/scenes/report/components/ObservationsReport.js, dashboard/src/scenes/stats/CustomFieldsStats.js, dashboard/src/scenes/stats/ObservationsStats.js, dashboard/src/scenes/stats/index.js
objectif: résoudre ces (gros) bugs que je n'ai pas réussi à reproduire localement:
- https://trello.com/c/8zAAkkVg/1308-bug-ema-emos-statistiques-dobservations-qui-matchent-pas
- https://trello.com/c/LgaLoVv3/1342-bugs-nombre-dobservations-de-territoire-nouveau-cr
en téléchargeant un export avec des données de debug qui nous aident, on pourrait comprendre le problème et éviter de demander la clé de chiffrement
on peut aussi en faire une feature :)
=> fix: more debug to observations

dashboard/src/types/organisation.ts
J'ai vu ça en codant du coup j'enlève
=> chore: remove unused and unassigned array

.github/workflows/playwright.yml, dashboard/src/components/ActionsSortableList.js, dashboard/src/components/DateBloc.js
=> chore: plus d'espace dans la liste d'actions et de consultations de nouveau compte-rendu

dashboard/src/scenes/report/list.js
=> fix: message d'abandon du compte rendu ancien

api/src/controllers/utils.js
=> fix: ajout d'un message de migration sur mobile
