- dashboard/src/scenes/auth/forgot.js
Hello,
Dans le cas où le mail renseigné ne correspond pas à un compte, actuellement le message d'info laisse croire au user que le mail renseigné va tout de même recevoir un mail. Comme ce n'est pas le cas, des users se plaignent de ne rien recevoir.
Je propose cette reformulation pour attirer leur attention sur le fait que s'il ne reçoive pas de mail c'est peut-être que ce n'est pas le bon mail qu'ils ont entré.
Bonne journée,
> Reformulation "password reset"

- .github/workflows/release.yml
- .k8s/__tests__/__snapshots__/kosko generate --env dev.ts.snap
- .k8s/__tests__/__snapshots__/kosko generate --env preprod.ts.snap
- .k8s/__tests__/__snapshots__/kosko generate --env prod.ts.snap
- .k8s/components/dashboard.ts
- .releaserc.yml
- README.md
- api/package.json
- api/src/config.js
- api/src/controllers/utils.js
- api/src/middleware/versionCheck.js
- app/android/app/build.gradle
- app/package.json
- app/update-mobile-app-version.js
Le but c'est de mettre à jour le package.json de l'API, du dashboard et du site automatiquement à chaque release. Mais pas celui de l'app mobile car il a un impact sur la mise à jour. On pourra voir plus tard comment gérer ce cas en attendant il faut continuer à le mettre à la main à chaque fois qu'on veut le livrer, même si il est ailleurs que le reste. J'ai des pistes pour améliorer. En attendant  : 
AVANT de merger cette PR : 
- api : 2.3.26
- dashboard : 2.3.28
- website : 2.1.18
- tag: 1.10.0
(4 versions différentes)
APRES avoir mergé cette PR : 
- api : 1.10.0
- dashboard : 1.10.0
- website : 1.10.0
- tag: 1.10.0
(4 versions pareilles, et plus de modifs à faire à la main dans les 3 fichiers)
WDYT?
> fix(ci): semantic release update package.json

- dashboard/src/scenes/organisation/view.js
https://trello.com/c/S7AqabGO/492-impossible-de-parametrer-les-champs-dans-orga-non-chiffrée
> fix(dashboard): show message for custom fields when organisation not encrypted

- dashboard/package.json
- dashboard/src/components/DateBloc.js
- dashboard/yarn.lock
Cette fois-ci ça va être bon !
Je me suis permis d'intégrer [`dayjs`](https://day.js.org/en/) (qu'on utilise aussi au SNU) et qui permet de manipuler les dates de manière plus agréable (je trouve). 
Maintenant pour décrire le problème et pourquoi je ne l'avais qu'à moitié résolu : 
En gros, d'après ce que j'ai compris, on stocke toujours les dates en UTC. Si on réutilise des fonctions de dates dessus, ça change tout le temps en réapliquant le temps du jour. Donc il faut à la fois récupérer la date en UTC **et** la manipuler en UTC (et ne jamais lacher ça). Ou alors appliquer une troncature pour retirer la timezone [comme ici](https://github.com/SocialGouv/mano/blob/main/dashboard/src/components/ActionsCalendar.js#L27-L35) mais ça fait plus hack. En fait peut-être que la solution aurait …
> fix(dashboard): fix utc problem for display date

- dashboard/src/components/search.js
- dashboard/src/scenes/search/index.js
Suite à un constat sur mon poste : 
Si je tape seulement 1 ou 2 caractères (je tape lentement), ça fait quasiment planter mon navigateur, parce qu'il y a trop de résultats et si je reprends à taper tout mon ordi part dans les choux
On peut considérer que la recherche commence à 3 caractères et qu'elle a un debounce un tout petit peu plus long.
Je trouve ça plus cool, mais dis moi.
> fix(dashboard): slow search

- dashboard/src/recoil/selectors.js
La liste des actions n'était pas liée à l'équipe sélectionnée.
> fix(dashboard): action list filtered

- api/src/controllers/organisation.js
- api/src/db/migrations/2021-11-16_observations-as-json.js
- api/src/db/migrations/index.js
- app/src/contexts/territoryObservations.js
- dashboard/src/components/TableCustomFields.js
- dashboard/src/recoil/territoryObservations.js
- dashboard/src/scenes/organisation/view.js
J'ai mis trèèèès longtemps avant de comprendre ce qui se passait.
En fait, pour une raison obscure, les `customFieldsObs` étaient stringuifiées. En résulte des opérations de stringification/déstringifications qui peuvent amener à des incohérence, car rien n'empèche de stringifier une chaine indéfiniment sans s'en rendre compte.
Du coup la solution proposée est de ne rien stringifier, vu que ce qu'on veut stocker c'est un objet et pas une chaine (les custom fields sont un array d'object, pas une chaine de caractères).
Le problème, c'est que comme actuellement les champs sont enregistrés en base de données pour les users en strings (sauf pour moi je ne comprends pas pourquoi), il faut garder une sorte de rétro-compatibilité d'où mon if chelou. Si tu as mieux je prends. On pourrait aussi …
> fix: customFields as object not string

- dashboard/src/app.js
- dashboard/src/scenes/auth/signin.js
- dashboard/src/services/api.js
Bon, je sais pas si c'est une "bonne pratique" ce que je viens de faire, mais ça a le mérite de marcher. Chez moi...
Contexte : j'ai un problème avec les hooks dans ma vie !
Je t'ai montré que de temps en temps, le state recoil se met à jour mais certaines fonctions utilisent toujours l'ANCIEN state recoil. Je n'arrive pas à comprendre pourquoi...
Certains ont cette [erreur sentry]( https://sentry.io/organizations/betagouv-f7/issues/2798886616/events/16be16eacf4c4e7294714e27cb8a4dd9/?project=5833236&query=is%3Aunresolved+%21bookmarks%3Ame): 4 users, mais 1400 fois.
Cause: `hashedOrgEncryptionKey === null` ce qui ne devrait pas être le cas.
j'ai donc pris une autre tactique pour ces cas particuliers, et ça marche.
J'aimerais bien ton avis !
> fix(dashboard): hashedOrgEncryptionKey === null even after setting good key

- dashboard/src/services/api.js
le drawer est disabled quand un admin se connecte pour la première fois et qu'aucune équipe n'est créée.
Je pense donc, sans avoir réussi à reproduire, que c'est parce que la requête `/teams` n'a pas fonctionné chez Nathan - il a réussi à reproduire plusieurs fois, mais toujours de manière aléatoire - je ne vois pas d'autre explication...
Donc voilà ma proposition : plus de retries, plus espacés !
J'ai vu que SWR essayait 10 fois, ça n'a pas l'air de faire de mal...
> fix(dashboard): drawer disabled when teams request fails

- dashboard/src/scenes/auth/signin.js
Objectif: finir cette "migration" consistant à créer le champ `encryptionVerificationKey`.
Objectif supérieur: en finir avec "déchiffrer quelques éléments pour voir si la clé est bonne", afin que l'erreur `ERROR DECRYPTING ITEM : Error: FAILURE` ait de nouveau du sens.
Problème: dans 3 orgas il semble que l'admin ne se connecte jamais, et donc n'active jamais `encryptionVerificationKey`.
Donc on va dire que pour ces 3 dernières, même un admin peut, si la clé qu'il a rentrée est bonne, créer ce champ.
> fix(dashboard): organisationEncryptionKey can also be setup by non-admin

- api/src/db/migration.js
- dashboard/src/recoil/selectors.js
- dashboard/src/scenes/reception/view.js
- dashboard/src/scenes/report/view.js
La situation actuelle:
-> chaque compte rendu a un champ passages qui compte tous les passages, anonymes et non-anonymes
-> chaque passage non-anonyme est un commentaire avec marqué "Passage enregistré"
-> si on supprime un commentaire "Passage enregistré", ça ne retire pas un passage dans le compte-rendu
Ce qui amène à
-> des incohérences si on retire des passages
-> des possibilités de bugs, de passages négatifs et autres
La future situation qui arrive
-> chaque compte rendu a un champ passages qui compte SEULEMENT les passages anonymes
-> chaque passage non-anonyme est un commentaire avec marqué "Passage enregistré"
-> de sorte que dans les deux types de passages sont indépendants : quand on retire un passage, on retire un passage ANONYME seulement (cf photo), et quand on retire un …
> fix(dashboard): passages

- dashboard/src/app.js
- dashboard/src/components/SelectTeam.js
- dashboard/src/components/charts.js
- dashboard/src/components/drawer.js
- dashboard/src/scenes/action/list.js
- dashboard/src/scenes/person/list.js
- dashboard/src/scenes/place/list.js
- dashboard/src/scenes/reception/view.js
- dashboard/src/scenes/search/index.js
- dashboard/src/scenes/stats/index.js
- dashboard/src/scenes/structure/list.js
- dashboard/src/scenes/team/list.js
- dashboard/src/scenes/territory/list.js
- dashboard/src/scenes/user/list.js
PR un peu mélangée (désolé 🐱), mais le principal but est de permettre de faire des stats par team / globales.
> feat(dashboard): stats orga and team

- dashboard/src/scenes/stats/index.js
Fix: https://trello.com/c/c1NdSPXf/529-stats-dashboard-certaines-stats-saffichent-en-double
> fix(dashboard): 2 stats repeated twice

- dashboard/src/recoil/selectors.js
- dashboard/src/scenes/report/view.js
- dashboard/src/scenes/stats/index.js
- dashboard/src/services/date.js
See: https://trello.com/c/4Lo5I14F/553-module-stat-bug-de-laffichage-des-passages
Exemple de "je me demande si on a besoin des selecteurs" : là j'ai du faire évoluer un sélecteur pour mon besoin et il est utilisé seulement à deux endroits maintenant et différemment. Je me demande si on n'aurait pas été mieux avec une fonction : `getPassages({startDate, endDate, team})` qui est une fonction utilitaire et qu'on peut mettre en memo. Bon tout ça pour dire que je suis pas très fier de mon code 😬
> fix: fix passages count in stat

- api/src/controllers/action.js
Remplace https://github.com/SocialGouv/mano/pull/346 de manière beaucoup plus simple.
Pour l'instant on renvoie 200 même si on ne trouve pas quand on delete. On verra après (suppression du relationnel pour l'encryption) comment on fait
Voir: https://trello.com/c/5OaWIjBA/549-bug-action-non-supprim%C3%A9e
> fix(dashboard): error deleting person due to casade

- api/package.json
- api/src/controllers/user.js
- api/yarn.lock
- dashboard/src/scenes/user/list.js
Cette PR est une preuve de concept sur une seule route avant de commencer à appliquer partout. J'ai décidé d'utiliser Zod pour la validation suite à ces messages (https://twitter.com/rap2h/status/1499313840303099908). Bonus, ce serait encore mieux avec du Typescript mais bon.
L'idée générale (qui est faite sous forme de démo ici) c'est : 
- On **valide côté back** sans tenir compte de ce qui a été fait côté front.
- La validation est dans un try/catch au début et **ne donne pas d'information** sur comment faire correctement l'appel à l'API (ce n'est pas une API publique, mais interne)
- On utilise dans **req.body** que ce qui a déjà été validé (par exemple en déstructurant)
- On ne se base **pas sur le front** pour obtenir les informations qu'on peut avoir autrement : exemple, on …
> fix: data validation

- api/src/controllers/public.js
- app/src/components/Loader.js
- app/src/components/ScreenTitle.js
- app/src/components/Search.js
- app/src/components/Tabs.js
- app/src/recoil/selectors.js
- app/src/scenes/Actions/ActionRow.js
- app/src/scenes/Actions/ActionsList.js
- app/src/scenes/Actions/ActionsTabNavigator.js
- app/src/scenes/Persons/PersonSummary.js
- app/src/scenes/Persons/PersonsSearch.js
- app/src/services/api-interface-with-app.js
> fix(app):  app perfs

- api/src/controllers/migration.js
- api/src/db/migrations/2022-03-07_add_migrations_in_organisation.js
- api/src/db/migrations/index.js
- api/src/index.js
- dashboard/src/components/Loader.js
@arnaudambro Je voulais faire la migration des commentaires vers de véritable passage, mais je pense qu'une première étape est de se mettre d'accord sur la façon de faire les migrations maintenant qu'on n'a plus les données. 
D'où cette PR (que je peux jeter). 
- Chaque organisation a une colonnes `migration` qui contient la liste des migrations faites
- Côté front, après le chargement des données (donc à la toute fin), dans le loader, on rajoute des `if` pour chaque migration vu qu'elle est de toute façon unique.
1. Vérification de si la migration est faite : 
`if (!organisation.migrations?.includes('passages-from-comments-to-table'))`
2. On met à jour le texte du loader (dont le progres est vers la fin, pas grave) : 
`setLoading('Migration des passages');` 
3. On fait les opérations …
> chore: migration from frontend data

- dashboard/src/recoil/selectors.js
- dashboard/src/scenes/action/list.js
Pour avis. Si c'est bon, next step, virer les autres sélecteurs inutiles des actions (il ne sont tous plus utilisés qu'une fois) et gérer du vrai state/memo/effect dans les composants en optimisant les mises en cache.
À ta dispo pour en discuter !!
> refactor(dashboard): PoC remove selectors

- api/src/sentry.js
En fait on ne peut pas utiliser le système dédié de sentry (https://docs.sentry.io/platforms/javascript/data-management/sensitive-data/) parce que c'est stringifié avant.
> fix(api): password disclosure in sentry

- dashboard/package.json
Inspiré par le support de browser du SNU. Autant en supporter plus vu le matériel des users (même genre que dans les institutions). Proposition donc : https://browserslist.dev/?q=PjAuMSUsZmlyZWZveCA%2BIDU1LG5vdCBkZWFkLG5vdCBvcF9taW5pIGFsbA%3D%3D
Source: https://github.com/betagouv/service-national-universel/blob/71e21b2765ebac55cfa2bcaa35c91393d52b70f4/admin/.babelrc#L10
> feat(dashboard): improve browser support

- dashboard/src/components/TableCustomFields.js
- dashboard/src/components/table.js
non. pas que je tenais absolument à modifier ce code, mais j'étais parti sur [Réglage des actions : Bug du tri des catégories d'actions](https://trello.com/c/UJmtrXdK/613-réglage-des-actions-bug-du-tri-des-catégories-dactions) et je me suis attaqué à ça au passage
finalement, le bug du tri n'existe pas !
donc c'est juste du nettoyage de code...
> chore: remove dataref and setup key to reset sortablejs state

- app/src/Navigators.js
- app/src/scenes/Actions/Action.js
- app/src/scenes/Actions/ActionsList.js
- app/src/scenes/Actions/NewActionForm.js
- app/src/scenes/Persons/PersonSummary.js
J'ai refait et j'ai privilégié le fait d'afficher la barre _tout le temps tant que le user n'a pas cliqué expressément_. **Tu peux tout à fait dire que tu n'es pas d'accord, je suis même chaud pour me ranger**. Mais finalement je suis convaincu par ton exemple de twitter, et par la proposition originale que tu avais faite : on reste là où on est.
J'ai l'impression que ça marche.
- Pour faire la correction, j'ai cherché partout où il y avait `screen` pour identifier les pages qui "restaient dans leur univers en partant ailleurs".
- Puis j'ai ajouté ces pages dans les stacks concernées
- J'ai viré les "person" et "action" globaux
- J'ai changé les navigations/push pour "rester au même endroit"
N'hésite pas à dire non ! Ton avis sur ces propositions est cool et tu as vachement plus …
> fix(app): loose bottom navigation bar

- CHANGELOG.md
- app/src/recoil/comments.js
- app/src/scenes/Comments/NewCommentInput.js
- dashboard/src/components/Comments.js
- dashboard/src/recoil/comments.js
- dashboard/src/scenes/report/view.js
`item` et `type` étaient utilisés au début, avant que `person` et `action` ne soient là
> chore: remove item field in comment

- dashboard/src/scenes/person/CreatePerson.js
- tests/src/__tests__/person.test.ts
Ça m'a aussi permis de repérer un bug que je vais corriger après : https://github.com/SocialGouv/mano/issues/558
Choix de design : j'ai directement proposé un selecteur rempli par défaut plutôt que de rattacher en coulisses pour éviter les comportements cachés ("ah bon ça associe à ma team, mais je ne veux pas moi... et surtout j'avais pas compris") et les questions plus tard ("alors en fait pour telle orga ils trouvent que le rattachement auto à la team en cours n'est pas adapté, ils voudraient un fonctionnement différent. Là ils sont obligé de créer puis éditer ensuite ...")
Ticket : https://trello.com/c/whdgxuCR/625-en-tant-quutilisateur-jai-besoin-que-le-dossier-de-la-personne-suivie-soit-automatiquement-assign%C3%A9e-%C3%A0-l%C3%A9quipe-avec-lauqelle-il-a
Pour l'instant c'est la …
> feat(dashboard): suggest team association when create person

- api/src/controllers/consultation.js
- api/src/controllers/migration.js
- api/src/controllers/organisation.js
- api/src/controllers/user.js
- api/src/db/migrations/2022-03-29_add_consultations_columns.js
- api/src/db/migrations/index.js
- api/src/index.js
- api/src/models/organisation.js
- api/src/utils.js
- dashboard/src/components/TableCustomFields.js
- dashboard/src/recoil/persons.js
- dashboard/src/scenes/organisation/view.js
- dashboard/src/scenes/person/MedicalFile.js
- tests/src/scripts/db.sql
- tests/src/utils.ts
J'ai ajouté la page de configuration des consultations dans l'onglet organisation. Et ça se répercute sur l'onglet "personnes suivies" -> "dossier médical"). C'est toujours uniquement visible en local. L'organisation a donc maintenant une propriété consultations sous la forme suivante : 
```js
[
{
"name": "Psychologique", // Il y a X types de consultations qui ont chacun un "name"
"fields": [ // A l'intérieur il y a des fields (comme d'habitude)
{
"name": "description",
"type": "textarea",
"label": "Description",
"enabled": true,
"showInStats": false
}
]
},
// ...
]
```
Et en fonction de ce qui est défini ça conditionne l'affichage du formulaire au moment où on remplit une consultations... Ça m'a forcé à adapter certains composants pour gérer le nested, j'espère ne pas avoir trop alourdi. …
> feat: custom fields consultation

- dashboard/src/components/PersonName.js
Actuellement comme on passe en bold au survol, ça fait danser le tableau, c'est un truc qui est plutôt évité le bold au survol. 
Pour que ça flash quand même j'ai mis comme un coup de stabilo. WDYT?
> chore(dashboard): change higlight mode to avoid table redimensionment

- api/src/controllers/action.js
- api/src/controllers/comment.js
- api/src/controllers/organisation.js
- api/src/controllers/passage.js
- api/src/controllers/person.js
- api/src/controllers/place.js
- api/src/controllers/relPersonPlace.js
- api/src/controllers/report.js
- api/src/controllers/territory.js
- api/src/controllers/territoryObservation.js
- api/src/db/migrations/2022-04-25_soft-delete.js
- api/src/db/migrations/index.js
- api/src/models/action.js
- api/src/models/comment.js
- api/src/models/passage.js
- api/src/models/person.js
- api/src/models/place.js
- api/src/models/relPersonPlace.js
- api/src/models/report.js
- api/src/models/territory.js
- api/src/models/territoryObservation.js
- app/src/components/Loader.js
- app/src/services/dataManagement.js
- dashboard/src/services/dataManagement.js
TODO
Avec ce code qu'on envoie, on a toujours des éléments supprimés dans l'app qui ne devraient pas être là.
Solution simple et utile pour l'avenir: gérer les versions de cache (je pense ? qu'en penses-tu ?)
Je voulais faire une chose simple mais ça marchait pas, donc je ne l'ai pas encore fait
Je pense surtout qu'on aurait intérêt à changer de lib MMKV pour aller vers une plus populaire et plus simple d'utilisation, et potentiellement qui marche mieux: https://github.com/mrousavy/react-native-mmkv (voir: [How is this library different from another mmkv?](https://github.com/mrousavy/react-native-mmkv/issues/100#issuecomment-886477361))
> feat: soft delete

- dashboard/src/components/ActionsCalendar.js
- dashboard/src/scenes/action/list.js
- dashboard/src/scenes/report/view.js
- dashboard/src/scenes/search/index.js
Expérience remontée par Nathan, intéressante
J'en ai conclu qu'il valait mieux retirer cette colonne : elle n'apporte de toutes façons pas une information très utile, et manifestement elle peut porter à confusion
https://user-images.githubusercontent.com/31724752/164717833-8a33db3b-a42a-444e-ae0c-7325c5964f2e.mp4
Je lui ai répondu
> Pour cette action:
-> tu l'as créée le 22 avril
-> elle doit être réalisée le 21 avril
-> tu es sur `Hier`, on est le 22 avril dont hier c'est le 21 avril
-> l'affichage calendrier est l'affichage des actions par date de réalisation
donc tout est normal pour moi
Je pense que tu as pensé qu'il y avait un problème parce que tu as créé une action pour la veille, ce qui n'est probablement pas si habituel que ça ? Là par exemple en face de moi, j'ai une action …
> fix(dashboard): hide createdAt column in actions tables

- dashboard/src/components/ButtonCustom.js
Parce qu'on voit pas toujours que c'est des liens (ça m'aide pour une future PR)
> fix(style): underline link on hover

- .kube-workflow/prod/values.yaml
ceci permet de bypasser le proxy d'authentification pour les routes utilisées dans les dashboards metabase publics (ex: stats publiques)
> fix(metabase): skip auth for public routes

- dashboard/src/components/Comments.js
- dashboard/src/components/ReportDescriptionModale.js
…on storage
https://trello.com/c/t260xtI0/715-enregistrer-lédition-dun-commentaire-en-sessionstorage
> feat(dashboard): save current comment and report description in session storage

- dashboard/src/components/DateBloc.js
@rap2hpoutre je pense que tu veux regarder ça : il semblerait que tu aies mis `dayjs.utc()` pour une bonne raison au départ !
peut-être que tu as mieux à apporter...
en attendant, je merge !
> fix(dashboard): remove utc on date display

- api/src/controllers/report.js
- app/src/scenes/Actions/Action.js
- app/src/scenes/Actions/NewActionForm.js
- app/src/scenes/Comments/CommentRow.js
- app/src/scenes/Comments/NewCommentInput.js
- app/src/scenes/Persons/Consultation.js
- app/src/scenes/Reports/Collaborations.js
- app/src/scenes/Reports/Report.js
- app/src/scenes/Territories/TerritoryObservation.js
- app/src/utils/useCreateReportAtDateIfNotExist.js
- dashboard/src/components/Comments.js
- dashboard/src/components/CreateActionModal.js
- dashboard/src/components/CreateObservation.js
- dashboard/src/components/DataLoader.js
- dashboard/src/components/Passage.js
- dashboard/src/components/ReportDescriptionModale.js
- dashboard/src/scenes/action/view.js
- dashboard/src/scenes/person/MedicalFile.js
- dashboard/src/scenes/reception/view.js
- dashboard/src/scenes/report/list.js
- dashboard/src/scenes/report/view.js
- dashboard/src/scenes/stats/index.js
- dashboard/src/services/useCreateReportAtDateIfNotExist.js
- tests/src/__tests__/report.test.ts
j'ai choisi une stratégie de custom hook parce que le code à reproduire à chaque fois est un peu long
```js
const useCreateReportAtDateIfNotExist = () => {
const currentTeam = useRecoilValue(currentTeamState);
const currentTeamReports = useRecoilValue(currentTeamReportsSelector);
const setReports = useSetRecoilState(reportsState);
const API = useApi();
return async (date) => {
const reportAtDate = currentTeamReports.find((report) => report.date === date);
if (!!reportAtDate) return;
const res = await API.post({ path: '/report', body: prepareReportForEncryption({ team: currentTeam._id, date }) });
if (!res.ok) return;
setReports((reports) => [res.decryptedData, ...reports]);
return res.decryptedData;
};
};
```
j'ai hésité avec un effect dans les atoms, mais j'ai trouvé que c'était mieux
je …
> fix(dashboard): create report only when activity on the day

- .github/workflows/release.yml
Utiliser la **deploy key** dans le secrets du repo plutôt que le PAT du Social Groovy bot
> chore: release without bot token

- dashboard/src/components/DateRangePickerWithPresets.js
3 mois glissants au lieu de 3 mois avant le mois courant
> fix: 3 months preset in stats

- api/src/controllers/report.js
- api/src/db/migrations/2022-11-29_add_reports_columns.js
- api/src/db/migrations/index.js
- api/src/db/relation.js
- api/src/models/report.js
- app/src/recoil/reports.js
- dashboard/src/recoil/reports.js
Comme on a dit
-> ça ne change rien au comportement actuel global, sauf que ça renvoie le compte-rendu déjà créé s'il existe
Question
-> est-ce qu'on ne mettrait pas non plus les services en clair aussi, au passage ? 
En tout cas c'est cadeau, si tu veux la merger de suite tu peux, avec release de l'app et forçage de MAJ aussi (j'ai demandé à Guillaume pour le faire mardi, parce que j'en avais marre des vieilles versions, il m'avait dit OK)
À lundi !
> fix: date and team in reports

- dashboard/src/components/DataLoader.js
use case où ça fonctionnait étrangement
1. je crée une observation de territoire : elle apparait en haut de la liste des observations 
2. je recharge ma page instantanément : la date de création de cette observation est ultérieure à la date du last refresh, donc elle sera téléchargée de la BDD
3. la fonction `mergeItems` place cette obs par défaut à la fin
4. vu que le nombre d'anciens éléments est le même que le nombre de nouveaux, il n'y a pas de tri
5. ma nouvelle obs apparait désormais en bas de la liste des observations
coût de cette PR: un peu plus de sorting, mais finalement pas grand chose puisque quand il n'y a pas de nouvelle donnée, il n'y a pas de tri inutile.
ce qu'on avait fait avant était plutôt de l'overengineering peut-être !
> fix: sorting items when loading

- app/src/recoil/selectors.js
- dashboard/src/recoil/selectors.js
Quand on supprime une famille et qu'il reste des commentaires ça fait péter les sélecteurs
> fix(dashboard,app): comment with no more group

- api/src/controllers/report.js
il y a parfois un écart de 2 ms entre la création du premier et du second compte-rendu, je me dis qu'au lieu de 1. checker si un compte-rendu existe et 2. le créer s'il n'existe pas, c'est peut-être trop tard. donc est-ce que la fonction `findOrCreate` ne ferait pas le boulot comme on le veut ?
quand je log la requête SQL ça fait:
```
Executing (d8a16bb0-a289-41a4-95df-0299bc15331b): START TRANSACTION;
Executing (d8a16bb0-a289-41a4-95df-0299bc15331b): SELECT "_id", "organisation", "date", "team", "debug", "encrypted", "encryptedEntityKey", "createdAt", "updatedAt", "deletedAt" FROM "mano"."Report" AS "Report" WHERE ("Report"."deletedAt" IS NULL AND ("Report"."organisation" = '00000000-5f5a-89e2-2e60-88fa20cc50bf' AND "Report"."team" = '8b18a173-f129-42ee-8724-494bd44e63b7' AND …
```
> fix(api): find or create report

- app/src/scenes/Persons/Person.js
Pour reproduire le problème : 
Modifier une personne, continuer à naviguer dans les screens de cette personne et re-sauvegarder cette personne. On perd potentiellement des infos et on revient dans un state différent.
J'ai mis trois heures à expérimenter des choses, et j'ai retenu une solution parmi d'autre, mais je challengerai bien le truc dans son ensemble pour voir ce qu'on a comme alternative.
La solution retenue est de listen via une callback aux changements de `personDB` pour ne pas reprendre une vieille version de `personDB` (ce qui arrivait actuellement)
Ça semble marcher mais ça vaut le coup de tester.
3 heures, 3 lignes.
> fix(app): person considered modified and losing previous info on focus

- api/src/controllers/person.js
Pourquoi cette PR ?
- ça fixe [MANO-2P](https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/61797/events/36a874c9f0f341b4ba87ce7061530b84/?project=52&query=is%3Aunresolved)
- quand un fichier est introuvable, c'est fort probablement parce que il appartenait à une personne qui a été fusionnée avec une autre, et qu'on avait pas anticipé ce problème et donc que le lien vers les documents lui appartenant a disparu. Il est donc perdu dans la DB... donc on peut peut-être assumer que: si on veut le télécharger, on prévient qu'il n'est plus disponible, et si on veut le supprimer, on peut dire qu'il l'est sans rentrer dans les détails
> fix(api): handle file not found

- api/src/db/migrations/2022-12-27_add-unique-constraint-on-report.js
- api/src/db/migrations/index.js
Bon déjà prenons le problème autrement : on ne devrait pas pouvoir créer de rapports en double ? Interdisons le en base de données.
Avec cette évolution, le seul impact sera que les utilisateurs recevront "Une erreur est survenue". Pas de rapport en double, et ils sont mis au courant que ça ne va pas. Un nouveau clic sur sauvegarder devrait régler le pb.
WDYT?
> fix(api): add unique constraint to avoid duplicate reports

- dashboard/src/components/tailwind/ActionsCategorySelect.js
- dashboard/src/scenes/action/list.js
- dashboard/src/scenes/stats/index.js
le seul malus du filtre dans l'agenda, c'est qu'il est différent des autres...
[EDIT]
en fait on a trois filtres possibles
- filtre uniquement par catégorie avec un react-select classique (on a dans personne/actions)
- filtre uniquement par catégorie avec le composant groupes/catégories (agenda)
- filtre par groupe puis par catégorie (statistiques)
bon, je propose de garder ça pour le moment, et d'en être conscient ! et si les gens se plaignent...
> fix(dashboard): allow filter by no category

- dashboard/src/scenes/person/components/Actions.js
- dashboard/src/scenes/person/components/Summary.js
PS: ne me demandez pas pourquoi ce que j'ai fait marche, je n'en sais rien. Mais vu que y'a que sur Safari que ça bug comme ça, je pense que c'est un bug de Safari, donc pas forcément besoin d'expliquer ? À vous de voir :)
En tout cas, vous pouvez tester que je n'ai rien pété !
ce qu'on cherche à retirer:
> fix: scrollbar on modal

- playwright.config.ts
Pourquoi ?
- pour aller plus vite dans l'exécution des tests
- parce qu'on dev plutôt sur Chrome, donc on teste pas mal déjà
- parce qu'on a qu'à tester sur chrome localement et sur firefox en github actions et ça devrait faire l'affaire
on remettre chrome si on se rend compte que ne pas tester sur chrome fait péter la production
> chore: stop testing chrome

- dashboard/src/scenes/team/list.js
J'ai corrigé le fait que le message "Veuillez créer une première équipe avant de commencer à utiliser la plateforme" s'affiche tout le temps même quand on n'est pas en onboarding. Ce message devrait s'afficher uniquement la première fois quand on crée une nouvelle organisation (car une première organisation est obligatoire).
Mais ça ne devrait pas s'afficher tout le temps.
> fix(dashboard): onboarding message for teams was always displayed

- dashboard/src/components/TableCustomFields.js
- dashboard/src/utils.js
- parce que Mélissa et Nathan s'en sont plaints quelque fois, et j'ai du changer à la main
- parce que pour certains types, y'a pas de raison de ne pas pouvoir changer finalement (genre tout ce qui est `string`)
> fix(dashboard): allow change certain types of custom fields

- dashboard/src/scenes/organisation/ActionCategoriesSettings.js
Ah ba je voulais modifier un truc concernant l'affichage et le fait de gérer le break des mots ça a changer aussi ce que je souhaitais faire dans une autre PR. L'affichage ne s'adaptait pas dans action alors qu'elle le faisait dans service. 
action : 
service : 
Bon là apparemment on est bon pour les mots et pour cet affichage...
> fix(dashboard): cut too long words without spaces in action

- dashboard/src/components/SessionCountDownLimiter.js
> fix(dashboard): le temps de session restant faisait légèrement danser l'écran

- dashboard/src/components/drawer.js
D'une manière générale pour retenir, il faut compter combien de morceaux qu'il y a dans la ponctutation. 1 = pas d'espace avant. 2 = un espace insécable avant et pas après.
> Oh ! Mais c'est bizarre, pourquoi on fait comme ça ? Je sais. Je ne sais pas ! Je pense : non ; si, oui.
En anglais c'est toujours collé
> Oh! That's weird, why do we have to do that way? I know. I don't know! I think: no; yes, yes.
Source : https://fr.wikipedia.org/wiki/Ponctuation#En_fran%C3%A7ais
> chore(dahsboard): en français les ponctuations doubles ont un espace insécable avant

- dashboard/src/scenes/person/OutOfActiveList.js
- dashboard/src/scenes/person/components/EditModal.js
- dashboard/src/scenes/person/components/History.js
note: 
suite à la carte https://trello.com/c/z3Qec0Tl/1023-bug-daffichage-de-lhistorique j'ai envoyé un hotfix  https://github.com/SocialGouv/mano/commit/257d8dfb7564f6781c66033b9b318d8988b5eff5 avec cette fonction:
https://github.com/SocialGouv/mano/blob/c3ac6326f7a3d03b945948825d6cbd9944735ddf/dashboard/src/scenes/person/components/History.js#L10-L17
je propose d'étendre cette fonction au-delà de la lecture de l'historique, et de cleaner l'historique à l'écriture aussi
refus entendable !
> fix(dashboard): retire une entrée buggée de l'historique, où on enregistrait la personne entière

- app/src/utils/search.js
- dashboard/src/scenes/reception/SelectAndCreatePerson.js
- dashboard/src/scenes/search/utils.js
- e2e/scripts/populate-db.ts
- e2e/search-with-accent-and-disorder.spec.ts
See: https://trello.com/c/12YDi3xO/1026-bug-saisi-recherche
Un peu de duplication tant qu'on n'aura pas statué sur ce qu'on attend de la recherche.
Je pense que le JSON n'est pas bon car par exemple si je tape "abd" pour "abdel" j'ai de grande chance d'avoir des UUID en tout genre qui ressorte ou des encrypted content. Bref ça fait des résultats surprenants.
> Rap2h
Bon je vais peut être pas factoriser, mais voilà le truc :
Celle de l’accueil “normalise” les mots (accents, etc.) et regarde sur le nom et la date de naissance
Celle de la liste des personne ne normalise pas les mots et regarde sur un json stringifié de l’item. Elle est utilisée pour tous les autres types de recherche.
Les deux ont des pour et des contres.
J’aurai tendance à privilégier la première mais avec plus de champs …
> fix(dashboard,app): possibilité de rechercher plusieurs mots dans le désordre pour retrouver par exemple une personne via nom prénom ou prénom nom

- dashboard/src/scenes/person/Places.js
devrait résoudre [MANO-9Z](https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/92113/?project=52&query=is%3Aunresolved&statsPeriod=14d)
> fix: rendre le champ Lieu obligatoire dans l'ajout d'un lieu fréquenté

- dashboard/src/components/TagTeam.js
- dashboard/src/components/TopBar.js
A tester si les couleurs semblent adaptées...
J'ai eu un bug lors du changement de noms d'une équipe (2 fois), l'équipe changeait de couleur, comme si l'ID se modifiait et ne se trouvait donc plus au même index dans le tableau (je l'explique comme ça mais cela venait peut être de modifications dans mon ordre des couleurs sans rafraichir etc... bref)...  Après avoir tout remis au propre, mis mes couleurs dans l'ordres etc..., je n'arrive plus à reproduire ce bug mais je vais refaire d'autre tests par précaution... A garder en tête si jamais... Ne pouvons nous pas ajouter un attribut couleur à une team le cas échéant ?
> feat(dashboard): ajout de 10 couleurs supplémentaires pour différenciation des équipes

- api/src/controllers/organisation.js
- api/src/db/migrations/2022-03-07_add_migrations_in_organisation.js
Plusieurs problèmes :
- Si on en croit ce fichier `api/src/db/migrations/2022-03-07_add_migrations_in_organisation.js` la valeur `custom-fields-persons-setup` n'est ajoutée dans migration que si la colonne migration n'existe pas. Ce qui n'arrive jamais, parce que la base de données n'est pas créée sauf pour les nouveaux devs.
- Les champs persos n'étaient pas ajoutés dans la base de données lors de la création d'une organisation. Enfin si : ils l'étaient au prochain déploiement grâce à `api/src/db/migrations/2023-01-19_custom-fields-person.js`. Mais c'est également absurde car ce "correctif" n'arrive que quand on redéploie le dashboard.
Bref maintenant quand on crée une organisation, on ajoute les champs persos.
Source : https://trello.com/c/YMh751zh/1041-quand-on-cr%C3%A9e-une-nouvelle-or …
> fix(dashboard): ajout des champs personnalisés par défaut lors de la création d'une nouvelle organisation

- dashboard/src/components/ActionsCalendar.js
- dashboard/src/scenes/person/components/InfosMain.js
- dashboard/src/scenes/person/components/PersonDocuments.js
- dashboard/src/scenes/person/list.js
- dashboard/src/scenes/person/view.js
- dashboard/src/scenes/structure/list.js
- dashboard/src/scenes/territory/list.js
fait :
- noms de structures dans la liste des structures
- adresses de structures dans la liste des structures
- noms de personnes dans l'agenda
- noms des actions dans l'agenda
- noms des territoires dans la liste des territoires (+ modif CSS vers Tailwind sur le fichier)
Correction ancienne PR : 
- noms trop longs sur fiche d'une personne
- noms trop longs sur la liste des personnes
ajout nouveau fix :
- modale de téléchargement document d'un personne
> fix(dashboard): mots trop long - utilisation de overflow:anywhere

- dashboard/src/scenes/person/components/EditModal.js
- dashboard/src/scenes/person/components/InfosMedicales.js
- dashboard/src/scenes/person/components/InfosSociales.js
Modale d'edition des champs dans la fiche de la personne (titre de champs trop long): 
description dans la fiche d'un personne avec un mot trop long 
titre ou champs de texte avec mot trop long sur la fiche d'une personne :
Il y a aussi un soucis sur la page de l'orga au niveau de la configuration des champs. J'ai fait une autre carte trello, dans une autre PR car y'a d'autres trucs de CSS a modifier
> fix(dashboard): mots trop longs -> editmodal + titre et texte info medicale et info sociale sur fiche d'une personne

- app/ios/Podfile
- app/ios/Podfile.lock
- app/ios/mano.xcodeproj/project.pbxproj
- app/package.json
- app/src/Navigators.js
- app/src/components/Loader.js
- app/src/recoil/actions.js
- app/src/recoil/comments.js
- app/src/recoil/consultations.js
- app/src/recoil/groups.js
- app/src/recoil/medicalFiles.js
- app/src/recoil/passages.js
- app/src/recoil/persons.js
- app/src/recoil/places.js
- app/src/recoil/relPersonPlace.js
- app/src/recoil/rencontres.js
- app/src/recoil/reports.js
- app/src/recoil/selectors.js
- app/src/recoil/territory.js
- app/src/recoil/territoryObservations.js
- app/src/recoil/treatments.js
- app/src/scenes/Actions/ActionsList.js
- app/src/scenes/Actions/ActionsTabNavigator.js
- app/src/services/api.js
- app/src/services/dataManagement.js
- app/src/utils/sortByName.js
- app/yarn.lock
> fix: performances du loader de l'app

- dashboard/src/scenes/stats/Reception.js
- dashboard/src/scenes/stats/charts.js
Avant : 
Après : 
La bande à droite se rétréci dans le cas où l'on met des mots trop longs et que l'on réduit un peu la fenêtre, du coup c'est pas hyper jolie... Peux tu tester et me dire ce que tu en penses ? Sinon j'essai de trouver une propriété pour éviter ça. On part quand même du principe que personne ne devrait mettre des noms à rallonge mais bon...
> fix(dashboard): noms de services trop longs dans l'onglet Accueil de la page statistique

- app/src/recoil/selectors.js
- app/src/scenes/Persons/PersonsList.js
l'idée: ne charger le super sélecteur que quand on en a besoin
sur ma machine de guerre, avec le super sélecteur ça met 500ms à charger initialement
sans ça met moitié moins de temps... pas gégé mais sur des machine moins bien c'est peut-être plus efficace
> fix(app): chargement plus rapide de la liste de personnes

- .kube-workflow/prod/values.yaml
- website/pages/_app.js
Message de Julien Bouquillon
> Hello  :slightly_smiling_face:
> 
> On aimerait améliorer les headers de sécurité HTTP sur les applications web de la Fabrique 
> 
>  Nous demandons à chaque équipe de bien vouloir :
> 
> - vérifier les headers HTTP de son frontend sur [Mozilla HTTP Observatory](https://observatory.mozilla.org/) ou [DashLord](https://dashlord-full.fabrique.social.gouv.fr/)
> 
> - faire le point sur les éventuels iframes/sites/urls externes utilisés dans vos frontends pour définir une [content-security-policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) adaptée
> 
> - ajouter les headers manquants sur son ingress ou son application, [petit tuto ici](https://socialgouv.github.io/support/docs/standards/securite#mettre-%C3%A0-jour-les-headers-http-de-mes-applications). …
> fix(dashboard): ajout des headers de sécurité (CSP et autres)

- dashboard/src/components/ActionsWeekly.js
Les actions sans heure et sur le premier jour de la semaine, ne s'affichait pas sur l'agenda hebdomadaire. 
cf carte trello : https://trello.com/c/jDj1U714 pour reproduire le bug.
> fix(dashboard): Action le premier jour de la semaine qui ne s'affichait pas sur l'agenda hebdo

- app/src/components/Loader.js
- dashboard/src/components/DataLoader.js
le loading des données est ainsi fait:
- T0: on check combien d’items ont changé depuis le lastLoadValue
- T0: si il y a des items à fetcher, on les fetch - ça prend X secondes (entre 1 seconde et 10 minutes en fonction du nombre d'éléments à aller fetcher) dans l’ordre suivant:
- personnes
- actions
- consultations
- …
- rencontres
- …
- commentaires
- T0 + X: on set lastLoadValue = Date.now()
Exemple problématique:
- T0: Il y a 10 commentaires à fetcher
- T0: Ce fetch dure 15 secondes, parce qu’on passe sous un tunnel et que la connection est très très lente
- T0+7: indépendamment de ce process, une rencontre est créée par ailleurs, sur un autre appareil
- T0+15: le fetch de 15 secondes fini, on set lastLoadValue = Date.now()
Conséquence: la rencontre créée à T+7 n’apparaitre jamais …
> fix(app, dashboard): mise-à-jour du ou au plus près de la requête du nombre d'éléments à mettre à jour

- app/src/Navigators.js
- app/src/recoil/reset.js
- app/src/scenes/Login/Login.js
bug actuel: quand on change d'organisation, on "additionne" les données des organisations au lieu de les remplacer, parce que on fait bien le clear du cache MMKV mais les states Recoil sont déjà initialisés et on ne les reset pas...
bug présent depuis https://github.com/SocialGouv/mano/commit/e1420a4dc9585818f0e5583d2b052f9f063c0298
> fix(app): reset du cache quand on change d'organisation

- e2e/restricted-role_V2.spec.ts
@marioonb Quelques changements (mais git s'embrouille dans les différences): 
- On utilise la date du jour plutôt que la date en dûr où tu as fait les tests, c'est surtout ça qui faisait buguer. Voir : https://github.com/SocialGouv/mano/pull/1412/files#diff-569ff5686195b29e10b9253d01fe2783224fabace47644d3d77240c1d49083aaR13-R19
- On utilise `await clickOnEmptyReactSelect(page, "territory-select-types", "Lieu de deal");` dès qu'il y a un sélecteur pour éviter de faire `await page.locator('.create-action-person-select__indicator > .css-tj5bde-Svg').click(); await page.locator('#react-select-person-option-0').click();` qui risque de planter une fois sur deux (et n'est pas facile à relire et maintenir)
- A chaque fois qu'on enregistre ou modifie quelque chose, on clique sur le toaster (`await …
> fix: test restricted role

- api/src/models/report.js
See: https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/96541/?project=52&query=is%3Aunresolved
Sequelize doit être mis au courant que la contrainte existe sinon il ne s'en rend pas compte on dirait
> fix: suppression du bruit dans sentry quand un rapport a failli être créé en double mano-ee

- dashboard/src/scenes/stats/Actions.js
- dashboard/src/scenes/stats/CustomFieldsStats.js
- dashboard/src/scenes/stats/Persons.js
- dashboard/src/scenes/stats/charts.js
- dashboard/src/scenes/stats/index.js
- dashboard/src/scenes/stats/utils.js
Dans cette PR qui concerne l'affichage des tableaux de stats pour les champs multi-choix
- on retire la ligne Total pour les champs multi-choix
- on affiche aussi les lignes qui combinent plusieurs multi-choix (exemple: si je consomme du crack et du cannabis, il y aura trois lignes: "crack", "cannabis" et "crack + cannabis"). Problème: on peut avoir plus de 200 lignes parfois, vu le nombre de combinaisons possibles... doit-on le laisser ?
TODO:
- fixer le click sur une ligne de combinaison de multi-choix, qui ne sélectionne plus les personnes concernées
> fix: retirer la ligne Total des champs multi-choix

- dashboard/src/components/TableCustomFields.js
https://trello.com/c/MvYhbsDO/1070-petit-bug-quand-on-modifie-un-champ-déjà-existant-sur-un-champ-fixe-devenu-personnalisable-qui-fait-disparaitre-un-choix-présent
Explication en commentaire dans la PR
> fix(dashboard): possibilité de renommer plusieurs fois un champ dans un choix multiple

- dashboard/src/scenes/stats/Consultations.js
- on crée un champ custo de consultation dans la section "Section 1"
- on crée une consultation de type "Section 1" et on renmplit ce champ custo
- on déplace le champ custo dans la section "Section 2" mais la consultation créée reste dans la section "Section 1"
Avant: dans les statistiques, le champ custo de cette consultation n'est pas pris en compte
Après: dans les statistiques, le champ custo de cette consultation est pris en compte
> fix(dashboard): on affiche la stat d'un champ custo de consultation quel que soit la section à laquelle il appartient

- api/src/controllers/organisation.js
- dashboard/src/app.js
- dashboard/src/components/ActionModal.js
- dashboard/src/components/DataLoader.js
- dashboard/src/components/DataMigrator.js
- dashboard/src/recoil/actions.js
- dashboard/src/recoil/comments.js
- dashboard/src/recoil/groups.ts
- dashboard/src/recoil/passages.js
- dashboard/src/recoil/persons.ts
- dashboard/src/recoil/places.js
- dashboard/src/recoil/relPersonPlace.js
- dashboard/src/recoil/rencontres.js
- dashboard/src/recoil/reports.js
- dashboard/src/recoil/selectors.js
- dashboard/src/recoil/territory.js
- dashboard/src/recoil/territoryObservations.js
- dashboard/src/scenes/auth/signin.js
- dashboard/src/scenes/person/Places.js
- dashboard/src/scenes/report/view.js
- dashboard/src/scenes/territory-observations/list.js
- e2e/activate_passages_rencontres.spec.ts
proposition:
Le dataloader ne gère pas le cache: c'est géré par Recoil à 100%, avec une valeur par défault `async` et un effect `onSet`. Ainsi, le dataloader ne gère que les states recoil.
Exemple: 
```js
export const territoriesState = atom({
key:'territory',
default: selector({
key: 'territory/default',
get: async () => {
const cache = await getCacheItemDefaultValue('territory', []);
return cache;
},
}),
effects: [({ onSet }) => onSet(async (newValue) => setCacheItem(collectionName, newValue))],
});
```
un exemple est plus parlant, reproduit pour chaque table
```js
let newItems = [];
setLoadingText('Chargement des personnes');
async function loadPersons(page = 0) {
const res = await API.get({ path: '/person', query: { ...query, page: String(page) } });
if (!res.ok || !res.data.length) …
```
> fix(dashboard): nouveau DataLoader

- dashboard/src/components/PersonName.js
- Tu es sur l'agenda, tu regardes toutes les actions, et il y en a une de "Monsieur X"
- Un autre utilisateur supprime "Monsieur X"
- Tu rafraichis tes données: ça plante
C'est "logique": on ne retire pas les actions même si on supprime une personne, pour garder une trace des actions passées
> chore(dashboard): clean comment

- .kontinuous/values.yaml
- api/src/controllers/migration.js
- dashboard/src/components/DataMigrator.js
- dashboard/src/components/VersionOutdatedAlert.js
je vois comme souci pour déployer le dashboard avant
- la migration pas prête côté backend
tu vois autre chose ?
> fix(api,dashboard): déploiement du dashboard avant l'api pour éviter que la bannière 'Rafraichissez svp' ne soit inutile

- .github/workflows/playwright.yml
pourquoi ?
- parce que les tests ne sont pas bloquants quand on déploie en prod de toutes façons
- parce que les tests nous intéressent surtout quand on fait une PR
- parce que quand on pousse directement sur `main`, dans les faits on s'en fiche des tests puisque c'est un hotfix qu'on veut être déployé avec ou sans tests
- parce que quand j'ai besoin d'envoyer un truc rapidement en prod comme il y a deux minutes, j'annule le workflow parce qu'il m'ennuie dans ce cas précis
- parce qu'en plus ça fait du bien à la planète de supprimer un truc dont on ne se sert pas
qu'en dis-tu ?
> chore: deactivate playwright on merge

- api/src/controllers/migration.js
- dashboard/src/components/DataMigrator.js
- dashboard/src/recoil/territoryObservations.js
j'ai un excerpt des données d'une organisation pour laquelle li y a un bug notoire de statistiques d'observations de territoires (https://trello.com/c/8zAAkkVg)
il se trouve que certaines observations ont un timestamp en guise de valeur de `observedAt`, d'autre rien du tout, d'autre une date ISO
c'est probable que le bug soit lié à ce problème
j'ai essayé rapidement de reproduire le problème, je n'ai pas réussi - je n'ai pas le temps de me pencher plus sur l'historique git ou quoique ce soit, donc j'abandonne
en revanche je suis optimiste pour la résolution du bug des stats
> fix: format observedAt proprement pour éviter un bug de tri dans les statistiques

- api/src/controllers/migration.js
- dashboard/src/components/DataMigrator.js
- dashboard/src/recoil/territoryObservations.js
- dashboard/src/scenes/auth/signin.js
PR "intéressante"parce qu'elle fait suite à un gros bug semaine dernière.
Contexte: j'avais fait une migration sur les observations de territoire parce que j'avais remarqué que certaines n'avaient pas de `observedAt`, d'autrews avaient un timestamp au lieu d'une date ISO, etc. donc pour harmoniser le tout, j'avais fait une migration... qui a foutu un sacré bazar: toutes les données custos avaient disparues !
j'ai compris pourquoi: c'est à cause de ce fichu `batch state` de react (https://react.dev/learn/queueing-a-series-of-state-updates#react-batches-state-updates)
qui faisait qu'au moment d'appeler [`const customFieldsObs = useRecoilValue(customFieldsObsSelector);`](https://github.com/SocialGouv/mano/blob/933ac50b070afd27ed6dbe7c39dcc3dd27755c89/dashboard/src/components/DataMigrator.js#L …
> fix: observations metadata

- dashboard/src/scenes/data-import-export/ImportConfig.tsx
- dashboard/src/scenes/organisation/view.js
- e2e/custom-fields_edit-choice.spec.ts
- e2e/custom-fields_edit.spec.ts
- e2e/custom-fields_toggle-by-team.spec.ts
- e2e/documents_organizer.spec.ts
- e2e/global_encryption-check-all-data-type.spec.ts
- e2e/persons_familles.spec.ts
Le développement est terminé, c'est prêt pour review :)
> feat: import/export de configuration (work in progress)

- dashboard/src/components/drawer.js
- dashboard/src/scenes/report/view.js
Du coup je filoute dans un premier temps, on enlève juste le lien et on laisse playwright continuer à exécuter l'ancient
> fix: suppression de l'ancien reporting
